### ISSUE TITLE
2000x2000 artwork option downloads 1200x1200 instead

### ISSUE THREAD

**Issue by Alex1331xela** [RemixDev/DRemixIssues#101]
**Describe the bug**
For both embedded and local artwork options, when set to 2000x2000 it will only download 1200x1200 , but when set to 1400x1400 it will download 1400x1400 like expected, confirming that there is a larger option than the 1200x1200 size it downloads when set to 2000x2000.

**To Reproduce**
1. Go to 'Settings > Artwork'
2. Click on 'Embedded Artwork Size' or 'Local Artwork Size'
3. Set to '2000x2000'
4. Download a track/album
5. Artwork will be 1200x1200

**Expected behavior**
Artwork to be the expected 2000x2000 size.

**Desktop (please complete the following information):**
 - OS: Windows 10 v1909, build 18363.476
 - Deezloader Version: 4.2.3 beta (commit da9f8b89ed)
 - Did you build it from the repo?: No, downloaded from Telegram

**Comment by trattaa** [comment]
It can also download 4000x4000, you need some kind of parser. If he did not find what was specified in the settings (for example, 2000x2000), then he starts sorting through: first 1900x1900, then 1800x1800, etc.

**Comment by RemixDev** [comment]
Deezers defaults not available image sizes with 1200x1200
I have no way of knowing the size of the cover until it's downloaded
Downloading multiple covers just to see if the cover is available in that size seems a dumb and resource intensive idea

**Comment by Alex1331xela** [comment]
Alright, that makes sense. Thanks for explaining how it works

**Comment by yellow-relo** [comment]
Hello, my remark was a bit more specific, it DL in 1400 if you set 1400, but it you set 2000, it either DL in 2000 if available,  or in 1200 (but not in 1400)

I don't get why if 2000 isn't available it fall back to 1200 and not 1400 (until 1400 doesn't really exist and is the result of upscaled 1200)

**Comment by RemixDev** [comment]
That's what deezer does
I have no choice on that

**Comment by yellow-relo** [comment]
Ok son deezer does the fallback? Ty for your answer.
