### ISSUE TITLE
Genre in mp3 file

### ISSUE THREAD

**Issue by trattaa** [RemixDev/DRemixIssues#103]
**Describe the bug**
Even when the option to save the tag in the file is turned off, it still downloads the file with the 'Genre' tag. This error only applies to mp3 file

**To Reproduce**
1. Go to ' 'Settings > Choose Which Tags To Save''
2. Uncheck the item 'Genre'
3. Download a track/album
4. No errors
5. Reboot back to the program
6. Download a track/album
7. See error

**Expected behavior**
Field tag 'Genre' must be empty.

**Screenshots**
![2019-12-01_145620](https://user-images.githubusercontent.com/44088228/69913608-cac0f480-144a-11ea-9732-62886598eadd.jpg)
![2019-12-01_145548](https://user-images.githubusercontent.com/44088228/69913609-ceed1200-144a-11ea-8470-5d813df6788a.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10 v.1909
 - Version 4.2.3 beta (commit da9f8b89ed)
 - Did you build it from the repo?: Telegram channel

**Comment by RemixDev** [comment]
That's the ID3v1 tag that gets defaulted to 0 (which is Blues)
Now if the tag is not selected it gets the value 255 (which I hope it's empty)

Fixed in commit [`7450f34851`](https://notabug.org/RemixDevs/DeezloaderRemix/commit/7450f34851fee853b01bb98a7a51d5ef6f32083d)
