### ISSUE TITLE
Can't open in macOS Catalina

### ISSUE THREAD

**Issue by eXCoreX** [RemixDev/DRemixIssues#104]
**Describe the bug**
Applications can't be opened in macOS Catalina 10.15.1

**To Reproduce**
1. Download Deezloader Remix 4.2.2 from telegram
2. Try to open it up

**Expected behavior**
Applications opens

**Screenshots**
<img width="540" alt="Screenshot 2019-12-01 at 15 05 30" src="https://user-images.githubusercontent.com/25376335/69914369-3c4d7280-144c-11ea-8175-c864ead4f14f.png">

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.1
 - Version 4.2.2
 - Did you build it from the repo?: No
 - If so which branch?:  -

**Log File**
Idk where it is.

**Possible Implementation**
maybe build 64-bit?

**Comment by RemixDev** [comment]
Read the FAQs please:

https://notabug.org/RemixDevs/DeezloaderRemix/wiki/FAQ#i-cant-open-the-app-on-mojave

**Comment by eXCoreX** [comment]
Oh, sorry, that's interesting. Why is it so, though?
