### ISSUE TITLE
Set case for tags

### ISSUE THREAD

**Issue by trattaa** [RemixDev/DRemixIssues#106]
Ability to set case for all tags or selected tags.
Case selection:
ALL IN UPPER CASE
all in lower case
**A**ll **W**ords **W**ith **C**apital **L**etter
**F**irst word with capital letter

**Comment by RemixDev** [comment]
And how would that be useful?

**Comment by trattaa** [comment]
Well, for example, the name of the track is written uppercase and that he corrects it

**Comment by RemixDev** [comment]
If a track is all uppercase it's because the artist wanted that to be all uppercase. Changing that would make the metadata not correct

example: deadmau5 would become Deadmau5.
The capitalization chosen by the artist would be incorrect

**Comment by trattaa** [comment]
I don’t argue about artists, although there are also incorrect case there
> https://www.deezer.com/en/artist/5209258

Still then for the name of the tracks it would have looked better
**FALL** -> **F**all
> https://www.deezer.com/en/album/117363532

**Comment by RemixDev** [comment]
But that's how the artist intended the track to be named...

Anyways
How were you planning on displaying the settings in the UI
Just adding a drop-down in the menu for each tag will create a huge mess

**Comment by trattaa** [comment]
Quickly made something like this would look
![2019-12-01_213419](https://user-images.githubusercontent.com/44088228/69918480-8867d980-1483-11ea-9595-07acc008af6a.png)
This will only affect items with text parameters:
Title
Artist
Album
Artist Album
Label
Unsynchronised Lyrics
Copyright
Publisher
Composer
Mixer
Author
Writer
Engineer
Producer
The tag that is inactive is accordingly inactive and the choice case.
The only thing I do not know how to make these names more compact.

**Comment by trattaa** [comment]
Who does not need to change the register, then leave the item "do not change"

**Comment by RemixDev** [comment]
For names use:
UPPER CASE
lower case
Start Case
Sentence case

Also your design is not doable with the current structure of that modal
Find something readable and usable on as many screens as possible

**Comment by trattaa** [comment]
And if in the 'Tags' settings, under the 'Date Format' and 'Year Format' selection field, add 'Case for Artist' and a 'Case for Title' with a choice:
Do not change
UPPER CASE
lower case
Start Case
Sentence case

**Comment by RemixDev** [comment]
14 drop-downs just for 1 feature seems a lot to me

Can't you just use an external tagger like mp3tag to do batch conversion on the files?

**Comment by trattaa** [comment]
![2019-12-01_224025](https://user-images.githubusercontent.com/44088228/69919220-c0731a80-148b-11ea-8952-4e7044ac946a.png)
No, you did not understand. Only 2 choices need to be left

**Comment by RemixDev** [comment]
That's doable
Will look into implementing that later

**Comment by RemixDev** [comment]
Added with commit [`5fbe7aa801`](https://notabug.org/RemixDevs/DeezloaderRemix/commit/5fbe7aa801672b3433ad5ab43f7d82c3087efabb)
