### ISSUE TITLE
Cloud Integration/ Featured Artists

### ISSUE THREAD

**Issue by Gargantua01** [RemixDev/DRemixIssues#107]
01. _**Cloud Integration**_

Would it be possible to download straight into a cloud storage, not downloading to phone or computer, essentially transferring from deezer.com servers straight to GSuite, MEGA or DropBox... this would be great for a number of things,
1 - Skip downloading and then having to manually upload
2 - in case deezloader is shut down you could have transferred all you wanted before
3 - I have 11 Terabytes of local storage, not everyone has that... and this would be great for storing thieir stuff online to stream
4 -  In the event deezer does something tot heir api which makes it impossible for you download song...
5 - it solves downloading and uploading in bulk if your internet is not the best

02. **_Featured _Artists__**

An issue i noticed is that when songs are downloaded for example
Major Lazer - Lean On (feat. DJ Snake & Mø)

it downloads as 
Major Lazer,DJ Snake,Mø - Lean On

which is just weird...

**Comment by selfhoster** [comment]
> 
>     Cloud Integration
> 
> Would it be possible to download straight into a cloud storage, not downloading to phone or computer, essentially transferring from deezer.com servers straight to GSuite, MEGA or DropBox... this would be great for a number of things,

This would require so much effort and work to support and maintain, I don't think this fits in the scope of the project, the use case seems very niche, and there's an easy alternative.

Simply use software to mount your cloud storage locally like [this.](https://cloud.google.com/storage/docs/gcs-fuse)

Pretty sure software like this exists for most cloud storage providers.

**Comment by eXCoreX** [comment]
Yeap, AFAIK, such an action requires some kind of buffer, so it would either be your computer, or (paid option, so I guess it won't happen) server running by author. I guess your best option is dropbox, as it has an ability to create a directory synced with cloud, like iCloud does. At least on Mac, I can choose this synced dropbox folder as download destination.

**Comment by RemixDev** [comment]
Feature request 1 won't be added
Feature request 2 you can try using different multiartist separator
Adding the name of the artist in the track name is bad practice
