### ISSUE TITLE
Song and Album not Downloading

### ISSUE THREAD

**Issue by Ruben2579** [RemixDev/DRemixIssues#108]
Hello, earlier today I was trying to download an Album, I clicked on the download button, and a couple of seconds later it would say it failed to download, I'm logging in, my WiFi's working, please fix this issues.

**Comment by RemixDev** [comment]
Please fill the template when creating a bug report.
Downloading "an Album" is not specific enough.

The album failed with what error?
(press on the error icon in the downloads tab to check it out)

On which OS are you? What version are you using

**Comment by Ruben2579** [comment]
Error: Error: EROFS: read-only file system, mkdir '/Queen'
And the version I'm using is: 2.5.6

**Comment by RemixDev** [comment]
This is not the repo for the Android version.

https://gitlab.com/Nick80835/DeezLoader-Android

**Comment by Ruben2579** [comment]
Oh oops sorry🤭🤭
