### ISSUE TITLE
Latest version don't open

### ISSUE THREAD

**Issue by DonnieDarko97** [RemixDev/DRemixIssues#110]
I'm having this problem, I update to the latest build and now deezloader appear in a blank screen, before this I was using a beta version and it was working for fine.
![Sin título](https://user-images.githubusercontent.com/58541073/70202726-4cd64500-16f9-11ea-80ca-97d7ca9493f3.png)

**Comment by RemixDev** [comment]
Read the FAQs before posting an issue

https://notabug.org/RemixDevs/DeezloaderRemix/wiki/FAQ#all-i-can-see-is-a-blank-screen
