### ISSUE TITLE
Plex and playlist/compilations

### ISSUE THREAD

**Issue by neckaros** [RemixDev/DRemixIssues#111]
Do you know how to properly set deezloader so that playlist are recognized as compilations in plex?

**Comment by neckaros** [comment]
It seems Plex is expecting the compilation flag in the id3 tags and the artist folder and id3 AlbumArtist to be Various Artists.
I don't see how to do this with deezloader

**Comment by selfhoster** [comment]
Have you tried the option "Save playlist as compilation"?

**Comment by neckaros** [comment]
Yes. I talked with @RemixDev on telegram and he will implement it in next release

**Comment by yellow-relo** [comment]
> Yes. I talked with @RemixDev on telegram and he will implement it in next release

It's already included in the last release (4.3.0)

**Comment by RemixDev** [comment]
There are some tags that need to be exact for compilations compatibility in plex

**Comment by RemixDev** [comment]
Fixed with commit [`fbb2c269bb`]https://notabug.org/RemixDevs/DeezloaderRemix/commit/fbb2c269bbddb649c16baf867ae5c30a91420b9c)
