### ISSUE TITLE
Composer file name template

### ISSUE THREAD

**Issue by HappyDreamsHobo** [RemixDev/DRemixIssues#112]
**Is your feature request related to a problem? Please describe.**
Arranging music by composer is important for classical music.

**Describe the solution you'd like**
Please add the composer template to tracknames / album tracknames / playlist tracknames.

**Describe alternatives you've considered**
No alternatives. 

Thank you very much.

**Comment by RemixDev** [comment]
Composer is not a consistent tag and it could break the folder structure
So won't add
