### ISSUE TITLE
Bug: Saving Playlist as Compliation does not save all tracks

### ISSUE THREAD

**Issue by RandomNinjaAtk** [RemixDev/DRemixIssues#115]
Latest version does not save all files, only 1 track will be saved and the album cover. Files are named as undefined...

This can occur using the default settings with saving playlist as compilation enabled.

example:

![image](https://user-images.githubusercontent.com/8386416/70377888-c895e480-18e7-11ea-819c-c7a7c25aed25.png)

**Comment by elagustinrojas** [comment]
Same problem here!
in logs i see this message:
`[Error] settingsRegex failed: TypeError: Cannot read property 'toString' of undefined`

if i disable "Save as Compilation" can download without problems

**Comment by RemixDev** [comment]
Can you send me all the templates in your settings?

**Comment by elagustinrojas** [comment]
Here is the entire config.json

`{
  "serverPort": 1730,
  "userDefined": {
    "downloadLocation": "E:\\Musica\\",
    "trackNameTemplate": "%artist% - %title%",
    "albumTrackNameTemplate": "%number%. %artist% - %title%",
    "playlistTrackNameTemplate": "%position%. %artist% - %title%",
    "createPlaylistFolder": true,
    "playlistNameTemplate": "%name%",
    "createArtistFolder": false,
    "artistNameTemplate": "%name%",
    "createAlbumFolder": true,
    "albumNameTemplate": "%artist% - %album%",
    "createCDFolder": true,
    "createStructurePlaylist": false,
    "createSingleFolder": false,
    "saveFullArtists": false,
    "padtrck": true,
    "paddingSize": "0",
    "queueConcurrency": 3,
    "maxBitrate": "3",
    "fallbackBitrate": true,
    "fallbackSearch": true,
    "downloadSinglesAsTracks": true,
    "logErrors": true,
    "logSearched": true,
    "createM3UFile": false,
    "changePlaylistName": false,
    "syncedlyrics": true,
    "minimizeToTray": false,
    "embeddedArtworkSize": 800,
    "localArtworkSize": 1000,
    "saveArtwork": false,
    "coverImageTemplate": "cover",
    "saveArtworkArtist": false,
    "artistImageTemplate": "folder",
    "PNGcovers": true,
    "multitagSeparator": "null",
    "dateFormat": "1",
    "dateFormatYear": "4",
    "savePlaylistAsCompilation": false,
    "removeAlbumVersion": true,
    "saveID3v1": true,
    "titleCasing": "nothing",
    "artistCasing": "nothing",
    "tags": {
      "title": true,
      "artist": true,
      "album": true,
      "cover": true,
      "trackNumber": true,
      "trackTotal": false,
      "discNumber": true,
      "discTotal": false,
      "albumArtist": true,
      "genre": true,
      "year": true,
      "date": true,
      "explicit": false,
      "isrc": true,
      "length": true,
      "barcode": true,
      "bpm": true,
      "replayGain": false,
      "publisher": true,
      "unsynchronisedLyrics": true,
      "copyright": true,
      "musicpublisher": true,
      "composer": true,
      "mixer": true,
      "author": true,
      "writer": true,
      "engineer": true,
      "producer": true
    }
  }
}`

**Comment by RandomNinjaAtk** [comment]
It can occur with default settings and no modifications made other than enabling saving as a compilation

**Comment by RemixDev** [comment]
Fixed with commit [`c27641e94c`](https://notabug.org/RemixDevs/DeezloaderRemix/commit/c27641e94c3c562a9fa21cc2f7b7a70ae3f61a42)
