### ISSUE TITLE
Album names template

### ISSUE THREAD

**Issue by elektraking** [RemixDev/DRemixIssues#118]
I see this settings field which had been available in the v4.2.2 has disappeared in the v4.3.0. I’ve tried to overcome it by using the backslash separator in the “Album tracknames template“ (like %artist% - %album% (%date%) %label% %upc%\%number%. %artist% - %title%) to create a separate folder, but it doesn’t work, it creates long file names including the “%upc%“ placeholders and the backslashes are replaced with underscores instead.

**Comment by RemixDev** [comment]
Just scroll down a little bit and use your eyes

**Comment by elektraking** [comment]
I got it, sorry.
