### ISSUE TITLE
Web UI Native Authentication & API Key

### ISSUE THREAD

**Issue by zhdenny** [RemixDev/DRemixIssues#120]
**Is your feature request related to a problem? Please describe.**
If you expose this service to the outside for remote access, there is no native authentication for the Web UI or the REST API. It would be excellent to see a native username/password for the Web Interface along with an actual API key as well for the REST API.

These features would provide a means for users to deploy this service on remote servers and access deezloader remix safely/securely.

**Describe the solution you'd like**
At a minimum, implement an API Key into the REST API. Then people can simply throw the Web UI behind something nginx htpasswd while still exposing the /api addresses securely.

**Comment by RemixDev** [comment]
Yeah, that's cool and all
But it's not the scope of the app

**Comment by zhdenny** [comment]
Ok. Understood.
