### ISSUE TITLE
Explicit tag is written as "ITUNESADVISORY"

### ISSUE THREAD

**Issue by Kai0ken** [RemixDev/DRemixIssues#122]
**Describe the bug**
When "explicit" tagging is set/active it writes in the tags as "ITUNESADVISORY" (might be, because you are using iTunes as source for this?), but it would be clearer if the "explicit" tag, would (like expected) write as "Explicit" in the tags. Just a small fix I guess?

**To Reproduce**
1. Go to 'Settings'
2. Click on 'choose which tags to save'
3. Click on 'Explicit' (to activete writing this tag into your file)
4. Download anything (does not matter whether you choose a single, album or whatever)
5. Look at the tags of your file(s)
6. See "ITUNESADVISORY" (with "0" for non-explicit or "1" for explicit)

**Expected behavior**
I expect that "Explicit" is written into the tags instead of "ITUNESADVISORY", because it is clearer (more obvious) and also the option-box literally says "Explicit".

**Screenshots**
[![Bild itl6j4y.png auf abload.de](https://abload.de/img/itl6j4y.png)](https://abload.de/image.php?img=itl6j4y.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version 18632
 - Did you build it from the repo?: 4.3.0 exe

**Possible Implementation**
Maybe just changing/overwriting/renaming "ITUNESADVISORY" to "Explicit"?

**Comment by RemixDev** [comment]
I only add tags if they are in the standard or standardized by players

If you can find a source that tells how to tag explicit songs that is supported by most players then I could try to change it

**Comment by Kai0ken** [comment]
Well, I do not except/want to a new tag to be added. I only asked for renaming (since it is not clear enough). "Explicit" or just "E" would be enough (instead of "ITUNESADVISORY").

![alt text](https://i.stack.imgur.com/nufMZ.png)
![alt text](https://i.stack.imgur.com/zlHJz.jpg)

**Comment by RemixDev** [comment]
As I already said

Find a valid tag name and I will change it
It must be a ID3 standard or a Vorbis Comment standard

**Comment by RemixDev** [comment]
Following mp3tag standard, the naming scheme is correct

https://help.mp3tag.de/main_tags.html

**Comment by Kai0ken** [comment]
Ah, okay. I have checked some sites, but unfortunately there is no "standard"/"official" way of tagging explicit songs (I'm really suprised). The "ITUNESADVISORY" seems to be exclusive for mp4's, but that is not a problem, since you are using them for "non-videos" too. 
For now we can close this thread until there will be a "standard"/"official" way of tagging explicit songs (maybe we'll have to wait some years or someone will ask ID3-Team or mp3tag-Team for introducing this tag officially soon).
