### ISSUE TITLE
Save Album Artwork not working

### ISSUE THREAD

**Issue by thmasker** [RemixDev/DRemixIssues#126]
A simple as that. I have the option enabled, but it won't work. On previous versions it would (before 4.3 update)

**Desktop:**
 - OS: Microsoft Windows 10
 - Version 1909 (OS Build 18363.535)

**Comment by RemixDev** [comment]
Saving artwork depends on your folder structure
Please provide more information

**Comment by thmasker** [comment]
So,
- Deezloader is there: D:\Program Files custom\Deezloader
- And the downloads folder in here: C:\Users\thmas\OneDrive\Music\Deezloader

Idk if this is the info you are expecting. I can provide any information else needed.

**Comment by RemixDev** [comment]
Is create album folder checked?
Is create artist folder checked?
Is create playlist folder checked?

**Comment by thmasker** [comment]
> Is create album folder checked?

Yes
> Is create artist folder checked?

Yes
> Is create playlist folder checked?

Yes

**Comment by RemixDev** [comment]
Can you provide a log file as well?

**Comment by thmasker** [comment]
I would have done so, but this option also seems to be unavailable... so I can't

**Comment by RemixDev** [comment]
What do you mean by unavailable?
Just paste the text in a pastebin and post the link

**Comment by thmasker** [comment]
I mean it does not create any log file, although the option is checked. Just the same problem as the one we are discussing

**Comment by RemixDev** [comment]
https://notabug.org/RemixDevs/DeezloaderRemix/wiki/FAQ#where-can-i-find-the-log-files

**Comment by thmasker** [comment]
```win32 - Windows_NT 10.0.18363 x64

[Info] Server is running @ localhost:1730
[Info] Connection received!
[Info] Checking for updates
[Info] Running the latest version!
[Info] Checking for country
[Info] Connection received!
[Info] Connection language set to: en
[Info] Logging in
[Info] Checking for updates
[Info] Running the latest version!
[Info] Logged in successfully
[Info] Loading Personal Playlists
[Info] Checking for country
[Info] Loaded 2 Playlists
[Info] Loading Personal Playlists
[Info] Settings updated
[Info] Loaded 2 Playlists
[Info] Added to Queue 880181
[Info] Registered track: 880181:9 | Elton John - Your Song
[Info] [Elton John - Your Song] Getting album info
[Info] [Elton John - Your Song] Getting BPM
[Info] [Elton John - Your Song] Downloading file to C:\Users\thmas\OneDrive\Music\Deezloader\Elton John\Your Song.flac
[Info] [Elton John - Your Song] Cover already downloaded
[Info] [Elton John - Your Song] Starting the download process
[Info] [Elton John - Your Song] Downloaded
```

**Comment by RandomNinjaAtk** [comment]
I'm also finding an issue with this, it is download the artwork but by default the name shows up as undefined.

If you attempt to change the naming to folder or cover or anything, it does not seem to set the name correctly

**Comment by RemixDev** [comment]
Have you tried the latest beta?

**Comment by RandomNinjaAtk** [comment]
yes, pulling from source. The field just shows as being blank, even if you edit and try to save.

**Comment by XEntombmentX** [comment]
I'm encountering the same issue despite having all three folder creation options enabled. Album folders aren't being created at all and the song files are just being put into the artist folder, which I assume is why the album art isn't there. This has been an issue as of installing 4.3.0 and occurs on both of my computers. Looking at the log, it appears it's downloading the album art, but it isn't showing up in the folders.

https://pastebin.com/VLhQQAfR

**Comment by RemixDev** [comment]
You're downloading a single track
Make sure the option for creating folders for single tracks is enabled

**Comment by XEntombmentX** [comment]
Ah, that was it. The wording of that option makes it seem as if it would be creating a separate folder for single tracks. It may be beneficial to change the wording, like "Create album folders for single tracks" or something along those lines. Thanks!

**Comment by RemixDev** [comment]
So can I close this?

**Comment by thmasker** [comment]
Well, it still does not work for me...

**Comment by RemixDev** [comment]
Album art gets saved only if the album folder gets created.
Make sure you have your option activated to:
Save album art
Create album folder
Create album folder for singles

**Comment by thmasker** [comment]
Oh that's right. Then I close it. Thanks!!
