### ISSUE TITLE
Need to see how I fixed a previous issue posted on NotABug

### ISSUE THREAD

**Issue by mR12KL** [RemixDev/DRemixIssues#129]
Very quick and funny issue: I solved an npm build error myself, but I can't remember how I fixed it! I remember it was very specific. Now I'm running into the same issue when building 4.3! Unfortunately, the "Issues" tab on NotABug now redirects here, so I can't see the issue anymore. BUT, I can still see my issue in activity!!

![wCpbshT](https://user-images.githubusercontent.com/16406485/71218117-5f6e8380-228e-11ea-9952-0e31af550232.png)

So I am assuming that you can still see the content of the issue. Could you paste what the solution to my issue was? thanks!!

Issue link: ```{notabug domain url}/RemixDevs/DeezloaderRemix/issues/178```

**Comment by RemixDev** [comment]
Fixed by doing the following:

- https://github.com/nodesource/distributions/issues/421#issuecomment-318560799
- reuploading repo
- npm install --unsafe-perm
