### ISSUE TITLE
Schedule Downloads

### ISSUE THREAD

**Issue by Gargantua01** [RemixDev/DRemixIssues#130]
I've been doing some discographies and its really tedious work trying to keep track of all those artists, i think a good solution would be to have the app scheduled to check monthly or weekly for new releases from artists you're following and have them downloaded automatically...

this could also work for downloading based on record label...
let me know what you guys, this would be very useful though.

**Comment by RemixDev** [comment]
That's not the scope of this app
You could use the REST API to make an app that solves your issue
