### ISSUE TITLE
Downloading flac song will get stucked

### ISSUE THREAD

**Issue by salad96** [RemixDev/DRemixIssues#134]
There's a bug when trying to download flac songs it will get stucked and never complete i try it with 5 songs and i have try clear cache,force stop

**Comment by RemixDev** [comment]
Have you tired the latest beta?

**Comment by salad96** [comment]
Hi i haven't because i always use the stable one gonna try to find the beta
to try

**Comment by salad96** [comment]
Hi i have solved the problem by going to setting and set the Path setting
to deezloader folder but now when i download a song it didn't show the
album art
