### ISSUE TITLE
REST API command to remove active download from queue

### ISSUE THREAD

**Issue by RandomNinjaAtk** [RemixDev/DRemixIssues#139]
**Is your feature request related to a problem? Please describe.**
Yes, sometimes downloads get stuck and do not finish. The only way to clear it up is to cancel the active download and that has to be done using the web app interface

**Describe the solution you'd like**
Just like you can check the queue via API command, it would be great to be able to send a cancel command to remove an active download.

**Describe alternatives you've considered**
Manually cancelling via web interface when used in server mode

**Additional context**
This will allow better automation via scripts because it will make it possible to clear stuck downloads automatically without user intervention.

**Comment by selfhoster** [comment]
Good idea, will add this in the coming days.

**Comment by selfhoster** [comment]
https://notabug.org/RemixDevs/DeezloaderRemix/commit/3097c0111d205cb8f33563d7d6a675ba42d5a995

https://notabug.org/RemixDevs/DeezloaderRemix/wiki/REST+API#remove-item-from-download-queue

**Comment by RandomNinjaAtk** [comment]
Thanks for that update, is it possible to implement cancel all queued items? It would be simpler then having to get the id, to send it for cancellation... It is to be used in this script... https://github.com/Migz93/lidarr-download-automation/tree/dremix

**Comment by selfhoster** [comment]
https://notabug.org/RemixDevs/DeezloaderRemix/commit/83709ab32a3c17e70d1a1dcadb8de4ab285b5651

https://notabug.org/RemixDevs/DeezloaderRemix/wiki/REST+API#clear-download-queue
