### ISSUE TITLE
Save playlist songs without playlist folder

### ISSUE THREAD

**Issue by SchwanzusLongus** [RemixDev/DRemixIssues#14]
I would like to have an option downloading playlist songs and M3U playlists to a own defined folder. I.e. C:\Downloads\<Album artist>\<Album title>\<title number> <title> . Not a folder named by playlist, cause most songs are in multiple playlists and would downloaded multiple times.

**Comment by RemixDev** [comment]
The filename and the path changes if you download an album or a single. The app should scan the entire music library to see if you've downloaded the song already, making the process of downloading playlist much much slower if you have a large library

**Comment by SchwanzusLongus** [comment]
Hi, sorry had a lot to do, last time. I don't know how to explain best. I don't mean, that it should scan directly if a song exist as album or single version. That duplicates are ok so far. But when I download multiple playlists, it downloads exactly the same file multiple times, cause every playlist get it's own folder. So same file exist multiple times in my HDD. I.e. SMLoadr loads several playlists, save playlist files to .m3u8, put songs into a root folder and skip identical files when they already exist.

**Comment by RemixDev** [comment]
Added with commit [`6dbe7b8ac6`](https://notabug.org/RemixDevs/DeezloaderRemix/commit/6dbe7b8ac67e1fde8d9632739ea090ccf9f8e9d1)
