### ISSUE TITLE
Add source and releasetype if possible.

### ISSUE THREAD

**Issue by Gamer4Life2020** [RemixDev/DRemixIssues#140]
**Describe the solution you'd like**
Would like the option in Tags to add Source like the address of the album or at least say Deezer.
So I have a reference later if needed, as to know its not a CD rip or whatever.

Also a release type would be nice as in album, single, ep, etc... for easier originating with script/picard.

Like how SMLoadr does. If not no problem, as I like this was more and being able to try to find an alternative to a missing track per country is nice. 

Thanks for this and all your work. As I mainly rip CDs but some new stuff/tracks are digital only.

**Comment by RandomNinjaAtk** [comment]
Release type is already available as a album naming template, ie: %type%, but not currently in tag form.

**Comment by RemixDev** [comment]
Could you provide the exact ID3 and Vorbis Comment for these tags?
Also with link to the reference if possible

**Comment by Gamer4Life2020** [comment]
> Release type is already available as a album naming template, ie: %type%, but not currently in tag form.

Thanks, I'll try that and see if it help with what I want to do for now.

**Comment by Gamer4Life2020** [comment]
> Could you provide the exact ID3 and Vorbis Comment for these tags?
> Also with link to the reference if possible

I'm don't know much on programming/scripting so this may or may not help. If not no problem just thought I would ask and that it may help others. From what I can see its only for FLAC so not sure if you would want to implement it or not as you can make tags on FLAC and not so much on MP3 as they have rules from what I read. This is from qodl reborn.

https://i.postimg.cc/T3gjSMM3/Release-URL.png

**Comment by jungletek** [comment]
I use an album names template (in the app's settings) that looks like this, for that reason:
`%artist% - %album% - [] - (%year%) - [WEB-%bitrate%]`

FYI, `%bitrate%` becomes either `FLAC` or `320` (etc.) depending on what was downloaded.

We can assume `WEB` is constant, as Deezer won't have 'rips' from CD or Vinyl, just the same tracks available digitally on other retail marketplaces.

**Comment by Gamer4Life2020** [comment]
> I use an album names template (in the app's settings) that looks like this, for that reason:
> `%artist% - %album% - [] - (%year%) - [WEB-%bitrate%]`
> 
> FYI, `%bitrate%` becomes either `FLAC` or `320` (etc.) depending on what was downloaded.
> 
> We can assume `WEB` is constant, as Deezer won't have 'rips' from CD or Vinyl, just the same tracks available digitally on other retail marketplaces.

I'll give that a try, but I have found plenty of FLAC from Deezer/Qobuz that are rips or at least accudatabase/cuetools are accurate. Here is just a few of them as I check them now ant then for fun.

Balque - Blaque
C-Murder - Best Of
Nivea - Complicated
SWV - Platinum ＆ Gold Collection, Greatest Hits
TLC - 20
3 6 Mafia - Most Known Unknown [Special Edition + Extra Tracks]
ICP - Flip the Rat, Fearless Fred Fury 
B_Witched - B_Witched
Lord Infamous - Fire & Ice
Paula DeAnda - Paula DeAnda
The Chainsmokers - Bouquet
The Chainsmokers - Sick Boy
QB Finest - Nas & Ill Will Records Presents Queensbridge the album
Hot Boys - Guerrilla Warfare
Hot Boys - Let Em' Burn
Mannie Fresh - Return of the Ballin
Eminem - Encore (Deluxe Version) 
Days of the New - The Definitive Collection 
Days of the New - Days of the New II
Eamon 
Suicide Squad_ The Album 
The Greatest Showman_ Reimagined (Deluxe) 
Beavis And Butt-Head Do America 

I'm going to go ahead and close this as it's not a big deal and just figured I would ask.
Thanks for all the work Dev.

**Comment by Gamer4Life2020** [comment]
> I use an album names template (in the app's settings) that looks like this, for that reason:
> `%artist% - %album% - [] - (%year%) - [WEB-%bitrate%]`
> 
> FYI, `%bitrate%` becomes either `FLAC` or `320` (etc.) depending on what was downloaded.
> 
> We can assume `WEB` is constant, as Deezer won't have 'rips' from CD or Vinyl, just the same tracks available digitally on other retail marketplaces.

I'll give that a try, but I have found plenty of FLAC from Deezer/Qobuz that are rips or at least accudatabase/cuetools are accurate. Here is just a few of them as I check them now ant then for fun.

Balque - Blaque
C-Murder - Best Of
Nivea - Complicated
SWV - Platinum ＆ Gold Collection, Greatest Hits
TLC - 20
3 6 Mafia - Most Known Unknown [Special Edition + Extra Tracks]
ICP - Flip the Rat, Fearless Fred Fury 
B_Witched - B_Witched
Lord Infamous - Fire & Ice
Paula DeAnda - Paula DeAnda
The Chainsmokers - Bouquet
The Chainsmokers - Sick Boy
QB Finest - Nas & Ill Will Records Presents Queensbridge the album
Hot Boys - Guerrilla Warfare
Hot Boys - Let Em' Burn
Mannie Fresh - Return of the Ballin
Eminem - Encore (Deluxe Version) 
Days of the New - The Definitive Collection 
Days of the New - Days of the New II
Eamon 
Suicide Squad_ The Album 
The Greatest Showman_ Reimagined (Deluxe) 
Beavis And Butt-Head Do America 

I'm going to go ahead and close this as it's not a big deal and just figured I would ask.
Thanks for all the work Dev.
