### ISSUE TITLE
Additional delimiter/separator support in artist tags

### ISSUE THREAD

**Issue by jungletek** [RemixDev/DRemixIssues#141]
Would be cool to have something like ` & ` (space ampersand space) as a separator in the artist tag field to save me a step when I have to fix tags.

Thanks for the work and improvements, and this awesome client.

**Comment by RemixDev** [comment]
Added with commit [a3fa031ae7](https://notabug.org/RemixDevs/DeezloaderRemix/commit/a3fa031ae74690b3f708ebab63e3318d0e962367)

**Comment by jungletek** [comment]
Thanks!
