### ISSUE TITLE
Newest development (commit) build break web app?

### ISSUE THREAD

**Issue by RandomNinjaAtk** [RemixDev/DRemixIssues#142]
**Describe the bug**
Running the latest development branch, get nothing but a blank web interface: 

https://notabug.org/RemixDevs/DeezloaderRemix/src/development

**To Reproduce**

**Expected behavior**
Load interface

**Screenshots**

![image](https://user-images.githubusercontent.com/8386416/72024767-29487200-3244-11ea-82b0-db9ae0245683.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 18.04
 - Did you build it from the repo?: No, running via node
 - If so which branch?: development

**Comment by RemixDev** [comment]
Try .`/clean.sh` and then `npm install`

**Comment by RandomNinjaAtk** [comment]
This is also reproducible using the telegram build on windows

**Comment by RemixDev** [comment]
Fixed with commit [`da9fc35abc`](https://notabug.org/RemixDevs/DeezloaderRemix/commit/da9fc35abc2b04b325d8bcbce7585e81433f5a54)

**Comment by RandomNinjaAtk** [comment]
Thx!
