### ISSUE TITLE
No Playlist Appears

### ISSUE THREAD

**Issue by Leboubou111** [RemixDev/DRemixIssues#151]
I've 3 playlist but nothing appears to PLAYLIST tab, same error when I tried to click on Refresh Playlist.
I've been connected to my account. My profile picture appear.

 - OS: Windows 10
Branche: Remix
Version: 4.3.0
Basé sur: Deezloader Reborn
Mainteneurs: RemixDevs Group

**Comment by RemixDev** [comment]
Are your playlists set to public?

**Comment by Leboubou111** [comment]
> 
> 
> Are your playlists set to public?

Yes.

And if I tried to search by name to "Search" tab, I can not find it.
It's named "Pas mal song" with 773 titles by Leboubou111

**Comment by Leboubou111** [comment]
Tried to rename playlist, same issue

**Comment by Leboubou111** [comment]
![image](https://user-images.githubusercontent.com/8314926/72926006-f6c66b00-3d53-11ea-9dcd-2716a36bb2e8.png)

Nothing appears in playlist tab.

Sorry, i'm a french user.

**Comment by RemixDev** [comment]
Seems like your profile is set to private

**Comment by Leboubou111** [comment]
> 
> 
> Seems like your profile is set to private

Oh, ok. Sorry. It's work fine after make my profile to public.
Many thanks.
