### ISSUE TITLE
Error: RangeError [ERR_OUT_OF_RANGE]

### ISSUE THREAD

**Issue by Uni-Crash** [RemixDev/DRemixIssues#152]
**Describe the bug**
The software is unable to properly download albums that have more than 255 titles. Up to title 255 it works but after that it throws the out of range error. Additionally the search will display an album with at least 256 titles as having 255 titles.

**To Reproduce**
1. Search for any album that has at least 256 titles (e.g. "Die Chemie des Todes (Ungekürzte Lesung)" by Simon Beckett).
2.a. Click on the download for the whole album and wait for the first 255 titles to be downloaded
2.b. or open the album's content and select any track with a number higher than 255.
3. The software will go through all titles, throwing an error for everything after track number 255. It will still create a file with the size of 0 KB for every title.
4. At this point things get unclear. If you do nothing and let it sit for a while it will still download some of the titles. I'm not sure but I think if you added them via the album download it will work while most of the time it doesn't work when downloading a selection of titles.
5. The files that it will download will have ID3 tags but Windows Explorer won't show them in detail view, only when opening the file's properties. Then after a while they suddenly appeared in detail view too in one case.

**Screenshots**
[Search](https://malzo.com/i/2020/01/26/rEj.jpg)
[Error](https://malzo.com/i/2020/01/26/rEi.jpg)

**Desktop**
 - OS: Windows 10 Pro Version 10.0.18362 Build 18362
 - Deezloader Remix version: 4.3.0
 - Did you build it from the repo?: No

**Log File**
It doesn't create a log file despite the option "Create log file for Errors inside the download folder" being turned on.

**Comment by RemixDev** [comment]
Fixed with commit [`d691877ecd`](https://notabug.org/RemixDevs/DeezloaderRemix/commit/d691877ecd2bbd450224e2ce73c31a6fafab6559)
