### ISSUE TITLE
cannot download some albums as flac

### ISSUE THREAD

**Issue by cappucino-cup** [RemixDev/DRemixIssues#153]
hello

with some albums i cannot download them as flac files

here 3 examples
https://www.deezer.com/en/album/249407
https://www.deezer.com/en/album/878952
https://www.deezer.com/en/album/40988

deezloder says:
Error: Song not found at desired bitrate.
mp3 320k works and other albums work as flac

when i listen to these albums with my deezer hifi sub. i get no info that these albums are
not available as flac. so they should be available as lossless.

would be nice if you could take a look at it.
may there is a small issue with the loader

(or deezer is cheating.... tidal and amazon hd show it when a file is not available in lossless)

thx

**Comment by jungletek** [comment]
This isn't a bug, Deezer just doesn't have everything in lossless format. Either it was never made available in that quality, or they don't have it for some reason (typically licensing-related, or a lack thereof).

Regarding 'indications' of audio quality, I don't think Deezer has any sort of visual indicator of whether tracks are available in lossless or not (I may be remembering incorrectly as I rarely use the site itself via the website).

IIRC DLRemix just determines what's available by trying to download lossless first, and if that fails, requesting an MP3.

**Comment by cappucino-cup** [comment]
thx for the info

the 3rd cd (40988) is also available at tidal
and at tidal as flac.

(the flac files from deezer and tidal servers are 100% identical for albums which are available on both services)
so i was a bit surprised that the same cd is available as flac at tidal but only as mp3 at deezer
i guess the record label sent the flac files to both....

if some cds at deezer are not available as flac 
deezer scams their customers....
hifi sup costs 20 €/$ and deezer doesn't say at there hp that some cds are not available in lossless...
and without deezloader nobody will ever find out.....

hard to believe deezer is doing this
so i guess the flac files are on their server somewhere....

are you 100% sure there is no bug with deezloader finding the flac files ?
may be the files have strange symbols or empty space in file name or something like that....

**Comment by RemixDev** [comment]
First check is done with the filesize Deezer provides
Second check is done with the actual file url

If it fails at the first check then Deezer is lying. If it fails at the second check then the track is really not available in flac

**Comment by cappucino-cup** [comment]
okidoki
and thx for the fast reply (and your great tool :-) )

just a small question....
i guess you have no plans to create a tool for amazon hd ?

amazon hd has an offline mode but flac files are encrypted and fragmented.....

**Comment by RemixDev** [comment]
Checked the albums and they are not available in flac. closing
