### ISSUE TITLE
Deezloader Remix 4.3.0

### ISSUE THREAD

**Issue by chrispadi** [RemixDev/DRemixIssues#154]
It's not possible to download in flac, it just freezes a few seconds from starting.

**Comment by RemixDev** [comment]
Have you tried the latest beta?

**Comment by sam-cross** [comment]
Working for me. @chrispadi try reinstalling or you could test the portable version.

**Comment by chrispadi** [comment]
Ok thanks, i'll try.

**Comment by starchild** [comment]
where is the option to choose flac?  I don't see it...

**Comment by chrispadi** [comment]
I did reinstall the version 4.2.0 and it works, sorry for the late response, thank you very much.
