### ISSUE TITLE
Add other format options to download songs

### ISSUE THREAD

**Issue by henriqueelder** [RemixDev/DRemixIssues#16]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by henriqueelder** [comment]
Would be good if we could download songs on another formats like aac (m4a), wav, alac, etc. .

**Comment by RemixDev** [comment]
Deezer only supports mp3 and flacs.
So I won't support any other format.
Won't add
