### ISSUE TITLE
The song Tusa does not appear in the search and not all the songs of Karol G or other artists, apart from missing many more songs and in better qualities, please solve this please.

### ISSUE THREAD

**Issue by Edushi** [RemixDev/DRemixIssues#160]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by RemixDev** [comment]
Are those songs available on Deezer?

**Comment by cappucino-cup** [comment]
this is a problem with deezers database.
(happens also with deeezer app and deezer homepage)

with several artists not all available albums/cds are shown when u list all albums.
when an album is not found try search for the song name
and the album with the song in it is shown (when the album is available)

**Comment by RemixDev** [comment]
That seems to be a Deezer API issue and not something I can fix

**Comment by cappucino-cup** [comment]
yep i think so

i wonder why you cannot show ALL available artist and album names (and may be even song names) in alphabetical order with deezer, tidal and amazon hd.
(like in a normal cd shop where cds are sorted by artist letter and then album letter :-) )
