### ISSUE TITLE
Downloading multiple tracks with the same title

### ISSUE THREAD

**Issue by vdgrty** [RemixDev/DRemixIssues#162]
**Describe the bug**
When downloading a song with the same title as another, the song doesn't appear in the downloads folder. Even though the song has a different length or is a different version.

**Expected behavior**
Tracks to download and if the title is the same, download with (1) or (2) etc.

**Additional context**
There may just be a setting I've missed in the options, but I can't figure this out.

**Comment by RemixDev** [comment]
You can just add another variable to the file name in the settings

**Comment by vdgrty** [comment]
> You can just add another variable to the file name in the settings

I'm a bit of a tech illiterate, could you explain what I'd need to do, please?

**Comment by RemixDev** [comment]
Open the settings
See where the track name template is
Hover the circled I
See which variables you can use
Add a variable that can distinguish different tracks with the same name

**Comment by vdgrty** [comment]
Alright, thanks
