### ISSUE TITLE
Grab better genre tags

### ISSUE THREAD

**Issue by akaleeroy** [RemixDev/DRemixIssues#17]
Deezer genre tags are terrible, most electronic music falls under `Electro` or `Dans`.

It would be great to provide a mechanism to grab correct genre / style tags from Discogs or Musicbrainz.

It's pretty much the only step left to be done before archival, and doing it with the likes of foo_discogs / MP3Tag / TagScanner / Picard / beetz is way too cumbersome for single tracks.
The place is right because the app is already writing tags, it has all the necessary context.

However I'm aware this is a significant enhancement, not sure if out of scope.

**Comment by RemixDev** [comment]
The scope of the app is to only get info from deezer. Adding extended tags is not planned for this application and I don't think it will.

Someone else suggested adding Spotify tags but that was closed as well.
So won't add.
