### ISSUE TITLE
360 by deezer download feature for deezloader

### ISSUE THREAD

**Issue by Superhackman** [RemixDev/DRemixIssues#175]
It would be great if deezloader allowed to download songs 360 by deezer (360RA of sony) and I was analyzing the traffic and what it generates is an mp3 that weighs around 30mb

link: http://e-cdn-proxy-3.deezer.com/mobile/1/bbbdf52a110eea58f5bf9fd257102f13e26e111a4b285248f456a885640a7ef040abb5f66e378940456b94c12c7acc387ee36aaa0ed2c97be6f03addb76c89460d4d4abb65c558b67f4243403665d348063ef54d67c219821901e1ef8d31ed56

http://e-cdn-proxy-9.deezer.com/mobile/1/e8d957877bab9be67c39ed89f6bcd19cb1429ebdc36e6aa61a13530101df0c661bb7b07fed28e8ca852050cf3d462810742ca07abde34df60ec771036ebe9a4c3423035a8ce69d1f406d76610898b3d3063ef54d67c219821901e1ef8d31ed56

but I think it is possible to decrypt, as this is encrypted

**Comment by RemixDev** [comment]
Already implemented
Right click download button

**Comment by Superhackman** [comment]
I already downloaded a song, but it has weird codec mha1 but it doesn't play just supports, do you know any?

**Comment by RemixDev** [comment]
The only working player is the Deezer 360 app itself
If you want to reverse it to find the codec for the format you could do that
