### ISSUE TITLE
Deezloader won't create folders for Albums

### ISSUE THREAD

**Issue by mina-gaid** [RemixDev/DRemixIssues#189]
**Describe the bug**
Deezloader does not create an album folder when the "Create folders for Albums" option is selected in Settings.

**To Reproduce**
Steps to reproduce the behaviour:
1. Enable the "Create folders for Artists" option in Settings with the template set to `%name%`
2. Enable the "Create folders for Albums" option in Settings with the template set to `%album%`
3. Download a song or album

**Expected behaviour**
An Artist folder will be created and inside it, an album folder with the album name should be created and Song(s) from that album should be downloaded inside that folder.

**Desktop (please complete the following information):**
 - OS: Windows 10 (Home)
 - Version 64 Bit
 - Did you build it from the repo?: No - Used Installer
 - If so which branch?: N/a

**What I tried**
 - Uninstalling and removing Temp files
- Changing settings to include different template flags other than `%album%`
- Different Desktop with the same OS and Settings

**Additional context**
This has been an issue since late 2019. Very likely to be associated with [this suggestion](https://github.com/RemixDev/DRemixIssues/issues/91) that resulted in [this Commit](https://notabug.org/RemixDevs/DeezloaderRemix/commit/6dbe7b8ac67e1fde8d9632739ea090ccf9f8e9d1).

**Possible Implementation**
Add Unit Tests to Source Code so settings don't break with each new version released.

**Comment by RemixDev** [comment]
I would like a logfile and a copy of config.json to debug this issue properly

**Comment by mina-gaid** [comment]
See here - [2020-03-14-15.28.34.txt](https://github.com/RemixDev/DRemixIssues/files/4332948/2020-03-14-15.28.34.txt)

**Comment by RemixDev** [comment]
I need to see the config.json as well

Do you have the setting create folder for single tracks enabled?

**Comment by mina-gaid** [comment]
```
{
  "serverPort": 1730,
  "userDefined": {
    "downloadLocation": "C:\\Users\\Mina\\Desktop\\Media\\Music\\Download\\",
    "trackNameTemplate": "%number% - %title%",
    "albumTrackNameTemplate": "%album%",
    "playlistTrackNameTemplate": "%number% - %title%",
    "createPlaylistFolder": true,
    "playlistNameTemplate": "%name%",
    "createArtistFolder": true,
    "artistNameTemplate": "%name%",
    "createAlbumFolder": true,
    "albumNameTemplate": "%album%",
    "createCDFolder": false,
    "createStructurePlaylist": false,
    "createSingleFolder": true,
    "saveFullArtists": false,
    "padtrck": false,
    "paddingSize": "0",
    "queueConcurrency": 25,
    "maxBitrate": "9",
    "fallbackBitrate": true,
    "fallbackSearch": true,
    "downloadSinglesAsTracks": true,,,
    "logErrors": false,
    "logSearched": false,
    "createM3UFile": false,
    "changePlaylistName": false,
    "syncedlyrics": false,
    "minimizeToTray": false,
    "embeddedArtworkSize": 800,
    "localArtworkSize": 1000,
    "saveArtwork": false,
    "coverImageTemplate": "cover",
    "saveArtworkArtist": false,
    "artistImageTemplate": "folder",
    "PNGcovers": false,
    "multitagSeparator": ";",
    "dateFormat": "1",
    "dateFormatYear": "4",
    "savePlaylistAsCompilation": false,
    "removeAlbumVersion": false,
    "saveID3v1": true,
    "titleCasing": "nothing",
    "artistCasing": "nothing",
    "tags": {
      "title": true,
      "artist": true,
      "album": true,
      "cover": true,
      "trackNumber": true,
      "trackTotal": true,
      "discNumber": true,
      "discTotal": true,
      "albumArtist": true,
      "genre": true,
      "year": true,
      "date": true,
      "explicit": true,
      "isrc": true,
      "length": true,
      "barcode": true,
      "bpm": true,
      "replayGain": false,
      "publisher": true,
      "unsynchronisedLyrics": false,
      "copyright": false,
      "musicpublisher": false,
      "composer": false,
      "mixer": false,
      "author": false,
      "writer": false,
      "engineer": false,
      "producer": false
    }
  }
}
```

**Comment by PhieF** [comment]
I also have this issue and IDV3 tags aren't saved, perhaps deezloader can't get artist/albums info anymore ?

**Comment by mina-gaid** [comment]
Fixed this. The issue was in the config.json.
For some reason, it was adding extra commas.

`"downloadSinglesAsTracks": true,,,`

To fix, I uninstalled Deezloader, deleted the Temp files in %APPDATA%. 
Now, I did this before but this time, I restarted my machine. Everything is working fine now.
