### ISSUE TITLE
Quick 'Preferred bitrate' selection on main window

### ISSUE THREAD

**Issue by agmmnn** [RemixDev/DRemixIssues#192]
**Is your feature request related to a problem? Please describe.**
I switch between flac and 320k so many times, sometimes I download a song in both options. And it's hard to get into Settings page every time. It would be more practical if it were on the main window.

**Describe the solution you'd like**
Maybe we can add the "Preferred bitrate" option in the Settings page to the top corner of the main screen. (2)

**Describe alternatives you've considered**
Or toggle button like 'dark mode slider'. (1)

**Additional context**
![Untitled-2](https://user-images.githubusercontent.com/16024979/77257452-7950a580-6c85-11ea-9292-e86f8dc849a3.jpg)

**Comment by bogol** [comment]
Right click the download arrow to quickly select preferred bitrate

**Comment by agmmnn** [comment]
oh my... i didn't know that. thanks! @bogol
