### ISSUE TITLE
Some tracks do not include covers

### ISSUE THREAD

**Issue by germar1985** [RemixDev/DRemixIssues#193]
**Describe the bug**
Since today May 25th I experience this bug. Some of the songs downloaded with Deezloader Remix v4.3.0 at mp3 320kpbs do not include the cover in the image metadata. With no success I also have tested downloading:
- at mp3 128 kbps audio quality.  
- a full album with "Save Album Cover" enabled.
- "Download images as PNGs".
- from another computer.

**To Reproduce**
Songs i have downloaded with no covers:
- Beauty & The Beats - Party (published on 2020-03-20)
- Basement Jaxx Red Alert (Jaxx Club Mix) from Red Alert (published on 1999-04-19)
- Basement Jaxx - Jus 1 Kiss (Radio Edit) from Jus 1 Kiss (published on 2001-09-24)
![Captura de pantalla 2020-03-25 a las 18 30 42](https://user-images.githubusercontent.com/59441010/77567029-d7200000-6ec6-11ea-8b1e-ccff464b4676.png)
![Captura de pantalla 2020-03-25 a las 18 31 13](https://user-images.githubusercontent.com/59441010/77567035-d9825a00-6ec6-11ea-8c9f-b876bf37fb8b.png)

**Desktop (please complete the following information):**
 - OS: macOS High Sierra 10.13.6
 - Did you build it from the repo?: I do not understand the question
 - If so which branch?: I do not understand the question

**Comment by RemixDev** [comment]
There are some issues with deezer's servers

If you have your cover size set to 2000x2000 lower it to 1400x1400 or 1200x1200
As not all covers are available in 2000x2000 and the fallback from deezer side stopped working

**Comment by germar1985** [comment]
Thanks RemixDev, changing the cover size works!
Do you have any estimation of when this deezer servers issues will be fixed?

**Comment by RemixDev** [comment]
It's not something I can do about, so I have no idea.
