### ISSUE TITLE
Button "Login with e-mail" greyed out in server mode

### ISSUE THREAD

**Issue by amenolo** [RemixDev/DRemixIssues#194]
**Describe the bug**
As per object, tested under Chrome and Firefox (cache/cookies cleared and so on...)

**To Reproduce**
1. Run as root
2. Go to 'Settings' in WebUI, section 'Deezer Login'
3. That's it

**Expected behavior**
Button "Login with e-mail" selectable.

**Screenshots**

![deez](https://user-images.githubusercontent.com/29974944/77595072-7d382e00-6ef8-11ea-8bf3-ce3abfb31506.png)

**Server:**
 - OS: Debian
 - Version: 10 with Node 13.11.0
 - Did you build it from the repo? Yes
 - If so which branch? Master v4.3.0

**Desktop:**
 - OS: Windows
 - Version: 10 1903

**Additional context**
Login with userToken runs well anyway.

Thanks!

**Comment by RemixDev** [comment]
That's not a big
That's intentional behavior

**Comment by amenolo** [comment]
On purpose in server mode, I gotcha you right?

I see....well maybe it's worth a quick mention in ufficial documentation, for instance under **Login button does nothing** FAQ section...

Thanks,
keep up the good work!

**Comment by RemixDev** [comment]
Yes, it's on purpose.

Login with email needs to open the captcha window, and that needs to be in an electron window, so it won't work in server mode
