### ISSUE TITLE
Multiple ARTIST tags for FLAC

### ISSUE THREAD

**Issue by mahc9kez** [RemixDev/DRemixIssues#195]
**Is your feature request related to a problem? Please describe.**

Multiple field names are supported in Vorbis Comment but DeezLoader Remix currently only use separator to write multiple names in one tag, usually in case there are multiple artists.

Separator are supposed to be used for MP3 because it does not support multiple names, but FLAC support multiple tags and it should be the preferred way for dealing with multiple names.

If FLAC files are tagged with multiple names, assume we are converting them to opus. `opusenc` keep the original multiple names. ffmpeg will convert it to single tag and separated by semicolon by default. Most of other software should process FLAC multiple names correctly.
But currently artists' names are saved in one single tag in FLAC, it's hard to get rid of separators and hard to convert to multiple names for formats which support multiple names.

**Describe the solution you'd like**
Support multiple names for FLAC, and show different "multitag separator" options depend on MP3 or FLAC been selected. forward slash for MP3 ID3v2.3, null character for MP3 ID3v2.4, multiple names or semicolon for FLAC.

**Describe alternatives you've considered**
1. Add an option in "Multitag Separator" section to use multiple names for FLAC only
2. enable this option each time when the format was changed to FLAC
3. Grey out the option and don't allow to select it when the selected format is MP3.
4. Still allow to select other separators such like semicolon for FLAC

**Additional context**

https://www.xiph.org/vorbis/doc/v-comment.html
```
Field names are not required to be unique (occur once) within a comment header. As an example, assume a track was recorded by three well know artists; the following is permissible, and encouraged:

              ARTIST=Dizzy Gillespie 
              ARTIST=Sonny Rollins 
              ARTIST=Sonny Stitt 
```

https://hydrogenaud.io/index.php?topic=73819.msg651342#msg651342

**Comment by RemixDev** [comment]
Change the multiartiat separator option to "null separator" or "default" if you're using the latest beta
