### ISSUE TITLE
Problem with cover

### ISSUE THREAD

**Issue by Marcoking98** [RemixDev/DRemixIssues#198]
**Describe the bug**
In the latest version it has started not to download the covers of some albums or singles. 

**To Reproduce**

**Expected behavior**
Normally, you download any cover of the single or album and embed it as a file.  Now he's not. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Android 
 - Version 9.0
 - Did you build it from the repo?:
 - If so which branch?: 

**Log File**
Upload your log file to pastebin and paste the link here, can be helpfull sometimes

**Possible Implementation**
Not obligatory, but suggest an idea for implementing addition or change

**Additional context**

**Comment by RaylaLe100** [comment]
it's not only the file but the cover is absent from the metadatas too

**Comment by RemixDev** [comment]
Stop using 2000x2000
It's not supported by Deezer anymore
