### ISSUE TITLE
Add option to rename playlist.m3u8 file

### ISSUE THREAD

**Issue by RemixDev** [RemixDev/DRemixIssues#2]
**Is your feature request related to a problem? Please describe.**
When you put these playlists files in the phone (at least this happens on Google Play Music), all playlists on the app are named as 'playlists' when they should be named as 'artist - album' or 'album' at least.

**Describe the solution you'd like**
It can be just a checkbox (Playlist m3u8 file with same name from folder)

**Comment by jaylex32** [comment]
I would love to see this feature asap. doesn't make sense to have a m3u8 file with playlist as a name.

**Comment by RemixDev** [comment]
Added with commit [`4b72598532`](https://notabug.org/RemixDevs/DeezloaderRemix/commit/4b725985323b7a1356e955c575c117accc6876d7)
