### ISSUE TITLE
Song preview not working

### ISSUE THREAD

**Issue by trishulc** [RemixDev/DRemixIssues#200]
**Describe the bug**
When pressing play on a song to preview it before downloading doesn't work no sound is playing

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows 10
 - Version 1909
 - Did you build it from the repo?:
 - If so which branch?: 

**Log File**
Upload your log file to pastebin and paste the link here, can be helpfull sometimes

**Possible Implementation**
Not obligatory, but suggest an idea for implementing addition or change

**Additional context**
This was working on 4.3.0 but im on latest beta version and doesnt work now.

**Comment by RemixDev** [comment]
Have you tried changing the preview audio level in the settings?

**Comment by trishulc** [comment]
> Have you tried changing the preview audio level in the settings?

Sorry didnt see that was a new option there. thanks
