### ISSUE TITLE
Download Error

### ISSUE THREAD

**Issue by Cabxxse** [RemixDev/DRemixIssues#205]
**Describe the bug**
Wen I try to download it shows an Error that says: Error: Authentication needed to get download URL

**To Reproduce**
1. Try to download any song
2. See error

**Expected behavior**
Download a song

**Desktop (please complete the following information):**
 - OS: Android
 - Version 2.5.8 and 2.5.9 (I've tried to download a song in both

**Log File**
  ##https://pastebin.com/ErArgKH8

**Comment by RemixDev** [comment]
Duplicate of #204

**Comment by Cabxxse** [comment]
Thx, that was a quick answer
