### ISSUE TITLE
FTP

### ISSUE THREAD

**Issue by julianborghuis** [RemixDev/DRemixIssues#207]
**Is your feature request related to a problem? Please describe.**
Yes, now i can not export directly to FTP

**Describe the solution you'd like**
I want that i also can set a ftp url as export folder such as:
ftp://USER:PASSWORD@IP:PORT/TO/YOUR/FOLDER

**Describe alternatives you've considered**
I have searched for bots that can do that but no progress

**Additional context**
Dont have

**Comment by RemixDev** [comment]
wont add

**Comment by julianborghuis** [comment]
why?
