### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by Gargantua01** [RemixDev/DRemixIssues#21]
I've noticed that some songs are available to stream on deezer but not on yandex and sometimes spotify, and alot of songs that're on yandex aren't on deezer... so im suggesting there be a quick option to switch to a yandex mode to search Music.yandex.ru for songs to download... there is a chrome extension that does this, "Yandex Music Fisher" but i do think it'd be a great addition to deezloader. also there is an option on music.yandex.ru to search by label as in "record label" if you clicked the record label at the bottom of the page on yandex music you could essentially all releases by that label... i've checked deezers site multiple times and there doesnt seem to exist an option to do this, im hoping you can find a way to do this within the app... also yandex music uploads music in mp3... and if its able to be downloaded by extensions i dont believe it should be a problem implementing it in the app. on the site its only available in 192kbps... maybe you can find a way to get the paid quality which is 320kbps... lastly can you add support for gaana.com indian streaming platform... and yes i am aware that somewhere ive read, i dont know if its you or another dev that said works are ongoing on a replacement for deezloader that support more streaming platforms than just deezer... thanks fror your time.

**Comment by RemixDev** [comment]
Deezloader means Deezer Downloader
There is no plan to add more platforms
