### ISSUE TITLE
Flac downloads are not the same a shown on the app menu

### ISSUE THREAD

**Issue by janmaroto** [RemixDev/DRemixIssues#23]
When downloading flac music it isn't downloaded at 1411kbps, as shown on the app menu, instead it is downloaded at 900kbps or less as shown on the down on the pictures. I have tried with different music like aretha franklin to lil nas x ed sheeran and david bowie.
Could someone please tell me if that's a common issue, if thats normal, or if it has any fix.?

thank you (: 👍
![Captura de pantalla 2019-08-02 a les 21 55 29](https://user-images.githubusercontent.com/43318495/62395924-fbaf1c80-b571-11e9-8f7a-3a6b319920e3.png)
![Captura de pantalla 2019-08-02 a les 21 55 53](https://user-images.githubusercontent.com/43318495/62395925-fc47b300-b571-11e9-9a28-8bad3a3c553e.png)
![Captura de pantalla 2019-08-02 a les 22 05 02](https://user-images.githubusercontent.com/43318495/62395926-fc47b300-b571-11e9-8175-244b10473f2e.png)
![Captura de pantalla 2019-08-02 a les 22 05 24](https://user-images.githubusercontent.com/43318495/62395927-fc47b300-b571-11e9-8526-10642a565916.png)
![Captura de pantalla 2019-08-02 a les 22 05 36](https://user-images.githubusercontent.com/43318495/62395928-fc47b300-b571-11e9-9eea-9e11c23da138.png)

**Comment by RemixDev** [comment]
It's not CBR, it's VBR where max peak it's 1411

If you decompress the Flac into a wave file you'll get the CBR file

**Comment by janmaroto** [comment]
I don't know what's CBR and VBR, but I'll find out.

Thanks for the help!!
