### ISSUE TITLE
Downloading error: Error: read ECONNRESET

### ISSUE THREAD

**Issue by Sample-User** [RemixDev/DRemixIssues#28]
**Describe the bug**
Unable to download almost any track.
Tried on diffent machines running Windows and Linux both using Deezloader Remix 4.2.2, even tried reinstalling them and deleting config folder.

**To Reproduce**
1. Search for a song
2. Download said song
3. Sometimes in the "Downloads" tab I can see a little download progress for a while but most of the times it fails immediately
4. Looking for errors it shows "Error: Downloading error: Error: read ECONNRESET"

**Expected behavior**
The track is downloaded

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 7/Linux Mint 19
 - Version: 4.2.2
 - Did you build it from the repo?: No
 - If so which branch?: -

Thanks a lot if you can look into this issue

**Comment by RemixDev** [comment]
Just tried to download something and it works fine.
Have you tried on other devices and on other networks?
Are you using a proxy or something like that?

**Comment by Sample-User** [comment]
Thanks for your reply.
Yes, I've tried on different machines with different OS as stated above, I've even tried using mobile data from my Mobile Carrier.
Searching for my error looks like is something from my end with connectivity but everything else works fine.

**Comment by onlysilent** [comment]
I'm not sure whether to post here or create a new issue, but I also seem to be having this issue. I never experienced it until last night. After downloading an artist with around 10 albums, I went to download another artist and started receiving erros. I went to sleep and tried again this morning and it worked perfectly with no issues. Now I see the issue while downloading another artist. Strangely enough, logging out and signing in with a different Deezer account I have seems to have worked. Downloading works perfectly.

Desktop (please complete the following information):

OS: Windows 10
Version: 4.2.2 Portable
Did you build it from the repo?: No
If so which branch?:

**Comment by KNTRO** [comment]
I'm experiencing this issue as well. The workaround I have found is to download track by track, which is a PAIN. Sometimes some tracks won't download and I have to retry several times until I get it.

**Comment by Skaronator** [comment]
This is definitely not a user problem. There can and will be network issues somewhere in the chain that the user can't control. And these kind of issues must be handled by the program.

My suggestion would be to build a retry mechanism that tries at least 3 times to download a song, if it still fails then its most likely a server issue or a really bad network.

**Comment by Skaronator** [comment]
Seems like the new download logic in the development branch fix this issue for 99% of the use cases.

**Comment by RemixDev** [comment]
As described in the OPs issue this should happen on every track, and it doesn't, so it's a user problem.

If you think there is another cause of this problem create a new issue
