### ISSUE TITLE
CLI commands for Deezloader Remix

### ISSUE THREAD

**Issue by Havock94** [RemixDev/DRemixIssues#29]
**Is your feature request related to a problem? Please describe.**
I would love to be able to send CLI commands to Deezloader Remix so that I can queue downloads from my own website page

**Describe the solution you'd like**
As SMLoadr does, it would be nice to have commands to start downloads from a Deezer URL via CLI command

**Comment by RemixDev** [comment]
Adding CLI support would require a total rewrite of the app, so won't add
