### ISSUE TITLE
does not show/load the images in the .mp3 files

### ISSUE THREAD

**Issue by Blitzet21** [RemixDev/DRemixIssues#31]
I recently reinstalled deezloader in my computer, then I downloaded a song and it doesn't show the image in the file, in old versions this problem didn't happen.

**Comment by RemixDev** [comment]
Log file?

**Comment by Blitzet21** [comment]
[2019-08-09-19.13.53.txt](https://github.com/RemixDev/DRemixIssues/files/3488357/2019-08-09-19.13.53.txt)


> 
> 
> Log file?

**Comment by RemixDev** [comment]
It seems like you're using an old commit
Try using the latest commit, where this bug is already fixed
