### ISSUE TITLE
Empty Spotify loved track playlist

### ISSUE THREAD

**Issue by Satris404** [RemixDev/DRemixIssues#32]
**Describe the bug**
While my Spotify account is linked to Deezloader Remix, when in the "playlist" tab, the "Loved track playlist" shows as empty.

**Screenshots**
![image](https://user-images.githubusercontent.com/29675522/62845201-36146a00-bc94-11e9-9b93-56eac14e9de1.png)

![image](https://user-images.githubusercontent.com/29675522/62845221-56442900-bc94-11e9-869b-d6666dc9c7ea.png)

**Desktop (please complete the following information):**
 - Running in the bocki docker container (https://hub.docker.com/r/bocki/deezloaderrmx)
 - Did you build it from the repo?: Yes
 - If so which branch?: Master

**Log File**
No error is showing in the logs. Not even a line specifying the playlist loading

**Comment by RemixDev** [comment]
The loved playlist is a deezer playlist
It has nothing to do with Spotify, so this is not a bug

**Comment by Satris404** [comment]
Hi,

So, is what is that playlist then? Is it containing the loved tracks from Deezer ?

In the other hand, that would be a very nice feature to have, a playlist containing all the Spotify liked tracks. What would be even more awesome is if, when Deezeloader is used as as a healess server, it would download automatically the new liked songs in Spotify.

**Comment by RemixDev** [comment]
Loved Tracks is a playlist containing loved tracks on deezer

Spotify's loved tracks are not public and can't be reached from the API without logging in and I don't want to add log in for Spotify so, won't add
