### ISSUE TITLE
Deezloader Remix 4.2.2 stuck on a blank screen

### ISSUE THREAD

**Issue by Rhoken** [RemixDev/DRemixIssues#33]
Deezloader Remix 4.2.2, installer or portable version doesn't matter, doesn't work properly on my Windows 10 x64 Build 1803. He stuck on a blank grey screen also for some hours. 

1. Delete all Deezloader/Deezloader Remix folder in %Appdata% (if you have any)
2. Install a fresh new install of Deezloader Remix 4.2.2 on Windows 10 x64 (installer or portable doesn't matter)
3. Run the application through the desktop shortcut
4. And simply wait 5 minutes, 30 minutes, one hour, some hours and nothing happen, he stay on a blank screen. 

I was expect a functionally program with the login screen with any or minor problems  

**Screenshots**
![StuckDeezloader](https://user-images.githubusercontent.com/54024308/62860374-48c48880-bd00-11e9-93cf-50369eee21b2.PNG)

**Desktop:
 - OS: Microsoft Windows 10
 - Versione x64 Build 1803

**Log File**
[2019-08-12-12.52.38.txt](https://github.com/RemixDev/DRemixIssues/files/3491965/2019-08-12-12.52.38.txt)

**Comment by Rhoken** [comment]
Is necessary to delete the DeezLoader folder in %Appdata% for simulate a install on a new system for the first time (so not a reinstall, but a newly install).

**Comment by RemixDev** [comment]
Try changing `serverPort` in `config.json` to `1930` instead of `1730`

**Comment by RemixDev** [comment]
Also try following the [FAQ](https://notabug.org/RemixDevs/DeezloaderRemix/wiki/FAQ#login-button-does-nothing)

**Comment by Rhoken** [comment]
Nope doesn't work. Same as before, the log file change only the port to "1930" instead of "1730".

FAQ i have just tried: i don't have any proxy active, no antivirus. antimalware, firewall completeley disabled, restart app, the Chrome things, restart PC.

**Comment by RemixDev** [comment]
Does it work if you open it in chrome? via `localhost:1930` or `1730` if you changed the port back

**Comment by Rhoken** [comment]
Nope, says "ERR_CONNECTION_TIMED_OUT"

**Comment by RemixDev** [comment]
Just tested this on clean install of Windows 10 1903 and it seems to work fine
Try updating windows

**Comment by Rhoken** [comment]
Updated at 1903 and now works.

Thanks

**Comment by King-Software** [comment]
I stuck on the same problem, but i can open the app at localhost. But when i try to open the .exe i only get a grey screen
