### ISSUE TITLE
Album Artwork - ability to change default name

### ISSUE THREAD

**Issue by Mamiac65** [RemixDev/DRemixIssues#35]
Issue:
When I play the file locally the player downloads new (Smaller size) artwork and overwrites the folder.jpg with a lesser quality. 

**Describe the solution you'd like**
I would love to be able to substitute the file name with a name of my own from a text field value. 
Example **Custom Album Artwork Label:** CoverArt    
This would result in all album artwork to be save as Coverart.jpg in the album folder instead of folder.jpg.    

**Describe alternatives you've considered**
Not though of an alternative as I want to preserve the larger artwork files for use with my juke box application. 

**Additional context**
I am sure others will find this valuable and some application can be set to allow for a particular filename to use for the artwork.  

Love the app!!! It keeps getting better and has save a lot of time!!! thank you!!!

**Comment by RemixDev** [comment]
It's already implemented, just open the options
:/
