### ISSUE TITLE
Explicit tag not included when downloading playlist files

### ISSUE THREAD

**Issue by knigget1** [RemixDev/DRemixIssues#40]
When downloading a playlist using the download all button (downward arrow) the explicit tag is not appended to filename of track. Only way around this is to open the playlist and download all files.

**Comment by RemixDev** [comment]
Fixed with [0d035d40a4](https://notabug.org/RemixDevs/DeezloaderRemix/commit/0d035d40a45f4215deb671df09d9dfc656aaf06b)
