### ISSUE TITLE
Erro no download de Album

### ISSUE THREAD

**Issue by AdailsonP** [RemixDev/DRemixIssues#41]
**Describe the bug**
Whenever I try to download an album hangs on some track and does not continue I need to keep restarting

**To Reproduce**
1. Open Deezloader
2. Search in "Albums"
3. Try downloading the album
4. Access the downloads tab

**Expected behavior**
I expected the download to be complete without errors

**Screenshots**
https://drive.google.com/file/d/1hd8Md8U62_-Gxkf6UWGWzZju0-YPCyIw/view?usp=sharing

**Desktop (please complete the following information):**
 - OS: [windows 10 pro]
 - Version [1809]
 - Did you build it from the repo?:
 - If so which branch?: 

**Log File**
--//--//--

**Possible Implementation**
Downloads

**Additional context**
Please, I really need it solved.

**Comment by RemixDev** [comment]
I need more information than "It doesn't work", also steps to reproduce this issue are too generic.
A log file could also be helpful.

If you're refering to errors like: Track is empty, Can't find alternative, etc...
It means that the track can't be downloaded because it's not on deezer servers

**Comment by Che-Max** [comment]
I ran into a similar problem in version 4.2.2 and 4.2.3-4353b8b031.
I download several artists discographies at once. I am looking for an Artist through the search and click Download Artist. Downloading starts, but after some albums it getting stuck on some track and all I see is an endless loading animation. No errors, no messages. 

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version 1909 (10.0.18363.448)
 - Did you build it from the repo?: No
 - If so which branch?: 

![Stuck](https://user-images.githubusercontent.com/56816178/67184032-76f2d280-f3eb-11e9-9b46-c8e49f8752b7.png)
[config.txt](https://github.com/RemixDev/DRemixIssues/files/3749457/config.txt)
[2019-10-19-00.13.03.txt](https://github.com/RemixDev/DRemixIssues/files/3749459/2019-10-19-00.13.03.txt)
[2019-10-21-01.43.53.txt](https://github.com/RemixDev/DRemixIssues/files/3749460/2019-10-21-01.43.53.txt)
[2019-10-21-04.15.49.txt](https://github.com/RemixDev/DRemixIssues/files/3749461/2019-10-21-04.15.49.txt)
[2019-10-21-04.17.05.txt](https://github.com/RemixDev/DRemixIssues/files/3749462/2019-10-21-04.17.05.txt)
[2019-10-21-06.12.22.txt](https://github.com/RemixDev/DRemixIssues/files/3749463/2019-10-21-06.12.22.txt)

**Comment by RemixDev** [comment]
A download doesn't start until the download before finishes

**Comment by RemixDev** [comment]
Also try to set queue concurrency to a lower value

I found out that 3 works best
