### ISSUE TITLE
Add individual album or track ID to each album / track

### ISSUE THREAD

**Issue by nhh24231** [RemixDev/DRemixIssues#44]
Possibility to add the individual **album** or **track ID** to each album / track.

Example:

Album name: "HIM - And Love Said No ... [**79333**]"
[https://www.deezer.com/en/album/**79333**](https://www.deezer.com/en/album/**7933**3)

Track Name: "01. HIM - And Love Said No [**637360**]"
[https://www.deezer.com/en/track/**637360**](https://www.deezer.com/en/track/**637360**)

For several albums of the same name with different releases, the albums will be saved correctly.

**Comment by RemixDev** [comment]
You can already do that using %album_id%
I'll make this work with tracks and playlists too

**Comment by RemixDev** [comment]
Added %album_id% %track_id% and %playlist_id% with commit [9835492889](https://notabug.org/RemixDevs/DeezloaderRemix/commit/9835492889eb2e95609565f48047f88fd8381ae3)
