### ISSUE TITLE
Better separation of artist 'Record Type'

### ISSUE THREAD

**Issue by bangsk** [RemixDev/DRemixIssues#45]
Some artists, particularly in the electronic genre, put out 'radio' shows. This clogs up the list of albums when viewing the artist modal dialog.

It would be nice to have some kind of filtering option for the artist dialog, be that checkboxes or a tabbed view.

For example, I might want to view the 'Single' Record Type only, but I have to scroll past a load of weekly radio shows to find them. In extreme cases, it means you cannot see the full list of their work.

An example artists: Cosmic Gate or Ferry Corsten - you can view their singles but they're quite far down past all their radio shows.

**Comment by RemixDev** [comment]
Added with commit [eb755c0489](https://notabug.org/RemixDevs/DeezloaderRemix/commit/eb755c04896e6d1e417627131c92601318a4b62d)
