### ISSUE TITLE
4.2.3 beta - Blank screen for me as well

### ISSUE THREAD

**Issue by janaxhell** [RemixDev/DRemixIssues#46]
Totally blank screen as i open Deezloader Remix.
I have not used it for a few days, then today it was totally blank and unusable, 
First I tried to update it with the latest beta from Telegram, but nothing changed.
Reverted to 4.2.2 and nothing as well.
Then I came here and read a post about the same problem on 4.2.2 version.
I have done *everything* suggested in that thread as well as the linked FAQ, but nothing helped.
Completely removed it with Revo Uninstaller Pro, that scans the system and deletes any debris and installed it from scratch. Still blank.
The weird thing is that this happened AFTER I accidentally deleted all my cookies with CCleaner, so I had to login again to Deezer (and all the other sites with a login). 
In that thread it is suggested exactly the opposite: to delete cookies to solve the problem.
I am on WIndows 10 Pro x64 updated right before coming here to write this (1903).
I use latest Vivaldi Browser, not Chrome.
I have been using Deezloader Remix for more than a year with linked Spotify account with no problem of sort. This is the first time I'm stuck with it.

![dlrmx](https://user-images.githubusercontent.com/55061479/64492827-e5833300-d278-11e9-89a9-8888000b16cb.png)

**Comment by RemixDev** [comment]
Log file?

**Comment by janaxhell** [comment]
Sorry, I'm not familiar with pastebin, is this ok?
https://pastebin.com/ktFgRDSJ

**Comment by RemixDev** [comment]
There's something else using port 1730
Try changing the port number to something else

Preferably between 49152-65535

You can change the port in config.json

**Comment by janaxhell** [comment]
Yes, it worked, thank you!
I wonder what took port 1730. I've tried to check with TCPView, but nothing is using it. 
Any way to find out?

**Comment by arlllk** [comment]
I also have that problem whit the last versions, but nothing have that port 
![image](https://user-images.githubusercontent.com/15748455/64889917-001c2a00-d634-11e9-98da-81b2ca033d95.png)

maybe the application have some other trouble to open that port

**Comment by RemixDev** [comment]
It's a windows problem only so I think it's something that Microsoft did in the last update
