### ISSUE TITLE
Why i had to Login everytime with the userToken? (headless-mode)

### ISSUE THREAD

**Issue by AlexanderSch90** [RemixDev/DRemixIssues#47]
Hey, i am running Deezloader Remix headless.
If i open the Web-Interface i must enter my userToken. 

Why is the token not saved? Why am I not automatically logged in?

Is it a Bug with the headless-mode?

Thanks for help!

**Comment by RemixDev** [comment]
Does your browser support Local Storage?
The token is saved there, if your browser doesn't support it it won't automatically log in

**Comment by AlexanderSch90** [comment]
ok, you're right, but would not it be possible to save the token on the headless server so I can access the headless server from all devices as easily as possible? Maybe a way to integrate this in the future?

Thanks for your work!

**Comment by RemixDev** [comment]
But what if 2 users want to use the same server with their playlists?

Also then anyone using that server would login with your account, creating a security issue
