### ISSUE TITLE
Linux: Running clean.sh breaks the app when using "yarn install"

### ISSUE THREAD

**Issue by Bockiii** [RemixDev/DRemixIssues#52]
After using "yarn install" on alpine linux, I can use "node /deezloaderremix/app/app.js" to start the application in server mode. If I try to use the clean.sh after the "yarn install", I get an error message about "express" missing.

1. Install packages "nodejs npm yarn git"
2. git clone the repo, run "yarn install" in the base directory. It builds correctly.
3. run "node /deezloaderremix/app/app.js", it will start correctly. Kill node
4. run the clean.sh script which deletes the node_modules etc
5 run "node /deezloaderremix/app/app.js". It will give you the error message that "express" module is missing.

**Expected behavior**
After the install, the excess data should be deletable to free up space.

 - OS: Alpine 3.10
 - nodejs v. 10.16.3
 - master archive.zip from the repo
 - Running in docker environment

**Additional context**
I've tried to use "npm install" but that breaks in more places than anything else. Yarn works fine until you try to remove excess data. So I have no idea if the clean.sh works if I install with npm because that has never worked for me.

I also get a warning during the yarn install : 
`warning electron > electron-download > nugget > progress-stream > through2 > xtend > object-keys@0.4.0:`
It still however works and I have not seen any broken functionality.

**Comment by Bockiii** [comment]
This is the dockerfile that's working btw:

https://github.com/Bockiii/deezloadermx-docker/blob/master/Dockerfile

The only thing that's happening that is not in the dockerfile is the start command (node /deezloaderremix/app/app.js)

**Comment by RemixDev** [comment]
yarn is not supported

Use non instead

**Comment by Bockiii** [comment]
I figured out the npm issue. Docker containers run all commands as root, so I had to do "npm install --unsafe-perm" in order to get it running.

But the behavior did not change.

Installation goes through, the tool works.

If I run the clean.sh script, I get this error message on starting the app.js:


```
internal/modules/cjs/loader.js:638


    throw err;


    ^



Error: Cannot find module 'express'


    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)


    at Function.Module._load (internal/modules/cjs/loader.js:562:25)


    at Module.require (internal/modules/cjs/loader.js:692:17)


    at require (internal/modules/cjs/helpers.js:25:18)


    at Object.<anonymous> (/deezloaderremix/app/app.js:12:17)


    at Module._compile (internal/modules/cjs/loader.js:778:30)


    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)


    at Module.load (internal/modules/cjs/loader.js:653:32)


    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)


    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

Any idea?

**Comment by RemixDev** [comment]
clean.sh cleans all modules folder, you should use that before using npm install
