### ISSUE TITLE
Sort Country Charts alphabetically

### ISSUE THREAD

**Issue by amresnake** [RemixDev/DRemixIssues#57]
Hello,
Thanks for the program, i think it will be helpful to **sort charts by country name**, this way you can find the charts you want easily.

Thank you

![Annotation 2019-09-28 151058](https://user-images.githubusercontent.com/55920188/65817680-334ce480-e202-11e9-9bbb-bf68437dc481.png)

**Comment by RemixDev** [comment]
Added on development branch
