### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by terrythetruck** [RemixDev/DRemixIssues#60]
I was searching for the following album called "Late Night Lute":
https://open.spotify.com/album/10giHBDpxwEeABP2a3tDyW

Searching "Late Night Lute" under "Albums" in DRemix, the album is not found. However I did find it by searching for the artist ("Matthew Wadsworth") where it appears in the search results.

I even tried enclosing the album name in quotes when searching.

Why would this happen?

**Comment by RemixDev** [comment]
Deezer search API suck ass

Nothing I can do about it
