### ISSUE TITLE
Autologin is not working

### ISSUE THREAD

**Issue by aikoofujimotoo** [RemixDev/DRemixIssues#61]
**Describe the bug**
Autologin doesn't work. Error:
```
Autologin failed: Can't connect to Deezer: JSON.parse(...).a.forEach is not a function
```
**To Reproduce**
1. Login your deezer account
2. Close Deezloader
3. Open it again and the error appears.

**Expected behavior**
It should login your account automatically.

**Screenshots**
![Screenshot from 2019-10-03 13-45-25](https://user-images.githubusercontent.com/35658068/66100155-ada3ad00-e5e4-11e9-8491-a8d65819aa8a.png)

**Desktop (please complete the following information):**
 - OS: elementaryOS 5.0 Loki (Linux, based from Ubuntu 18.04.2 LTS)
 - Version 4.2.2
 - Did you build it from the repo?: yes
 - If so which branch?: master

**Comment by RemixDev** [comment]
reinstall dependencies, fixed with latest commit on deezer-api
