### ISSUE TITLE
Artist tags are a mess

### ISSUE THREAD

**Issue by LPW00** [RemixDev/DRemixIssues#63]
The artist tag is sometimes filled up with individual bandmembers, the writer(s), composer(s) and what not, at least that's what i guess these names are. "Write all artists in track filename" is obviously disabled. The really interesting thing is, it doesn't happen on all albums and there's no pattern to connect the albums with that problem.  I use deezloader-remix-bin from the AUR.

**Comment by RemixDev** [comment]
Can you post the links that cause this issue?

**Comment by LPW00** [comment]
> Can you post the links that cause this issue?

yeah, sure. For example this album: https://www.deezer.com/de/album/42221801 it's from a band and after the band name, every bandmember is listed individually in the artist tags.
another example is almost every album from Logic, though i don't know, maybe he features at least 5 people on every track? who knows...

**Comment by RemixDev** [comment]
Just to be sure
Downloading just the track gives the correct number of artists right?

Also write all artist in track file name is just for filename, not tags. It's not related to this problem

**Comment by LPW00** [comment]
> Just to be sure
> Downloading just the track gives the correct number of artists right?
I don't know tbh. I haven't tried that. 
> Also write all artist in track file name is just for filename, not tags. It's not related to this problem
Didn't know that

**Comment by LPW00** [comment]
Okay, yes, downloading just one individual track works. It's tagged as it should be

**Comment by RemixDev** [comment]
fixed with commit [`fed2269127`](https://notabug.org/RemixDevs/DeezloaderRemix/commit/fed22691279e1070cf4ad878e5b742eb4b44eb70)
