### ISSUE TITLE
Deezloader Deleting folder with username

### ISSUE THREAD

**Issue by direstraits96** [RemixDev/DRemixIssues#64]
**Describe the bug**
After using Deezloader several times, Deezloader 4.2.2 will start deleting a folder with your username in same exe directory.

**To Reproduce**
1. Create a folder with your username where Deezloader exe is located
2. Use Deezloader
3. After several uses the folder will be deleted

**Desktop (please complete the following information):**
 - OS: Windows 7 x64
 - Version: 4.2.2
 - Did you build it from the repo?: No

**Additional context**
Deezloader 4.22 Windows Portable x64

**Comment by RemixDev** [comment]
This seems an electron / electron-builder issue, not a deezloader one
