### ISSUE TITLE
Incorrect explicit tagging

### ISSUE THREAD

**Issue by DeathHackz** [RemixDev/DRemixIssues#65]
**Describe the bug**
When downloading a song the song is tagged explicit based on its album. If the song's album is explicit, the song will be tagged explicit regardless if the song itself is not explicit. For example, if an explicit album has a clean song in it the song will be tagged as explicit despite the song being clean.

**To Reproduce**
1. Search for ''One Dance" by Drake
2. There are two results, chose the one that is a part of the explicit album "Views"
3. Download the song
4. The song has been tagged explicit despite it being a clean song

**Expected behavior**
When tagging song's explicit it should be based on the song itself, not the album it is a part of. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 4.2.2
 - Did you build it from the repo?: No

**Possible Implementation**
Tag explicit songs based on the song itself, not the album it is a part of.

**Comment by RemixDev** [comment]
This bug is already fixed in the development branch
Use the betas to check if it's really fixed

**Comment by RemixDev** [comment]
Betas link:
t.me/DeezloaderRemixBeta

**Comment by DeathHackz** [comment]
I just checked the beta, and it has been fixed.
