### ISSUE TITLE
Accessibility: Focus Search Input.

### ISSUE THREAD

**Issue by alivefromupstairs** [RemixDev/DRemixIssues#66]
I use the keyboard heavily. to focus the search input without reaching for the mouse, I have to press tab for a good 2 seconds and adjust. I don't know what's consuming the tabindex, but to focus the search input by default seems pretty reasonable for me. Or better yet, `ctrl-l` to always focus (and select all) search input like browsers do.

one minor thing unworthy of its own issue is that the scrollbar should be positioned fixed to not cause a jitter between unpopulated and populated tabs.

**Comment by RemixDev** [comment]
Added with commit [`bb85453ae2`](https://notabug.org/RemixDevs/DeezloaderRemix/commit/bb85453ae255bedfda5cfa4460a4e541902c579a)
