### ISSUE TITLE
File Naming, add Album Artist ID to Artist folder naming

### ISSUE THREAD

**Issue by RandomNinjaAtk** [RemixDev/DRemixIssues#67]
**Is your feature request related to a problem? Please describe.**
Multiple artists can end up in the same artist folder due to having the same exact name.

**Describe the solution you'd like**
Add Album Artist ID for to Artist folder naming

**Describe alternatives you've considered**
Manual fix

**Comment by ntcarver0** [comment]
This would be really nice to have.

**Comment by RemixDev** [comment]
Added with commit [`6dbe7b8ac6`](https://notabug.org/RemixDevs/DeezloaderRemix/commit/6dbe7b8ac67e1fde8d9632739ea090ccf9f8e9d1)
