### ISSUE TITLE
App localization

### ISSUE THREAD

**Issue by RemixDev** [RemixDev/DRemixIssues#7]
Right now the app is english only and it's hardcoded that way.
I need to find a way to make the app localized in multiple languages.
Help needed.

**Comment by LaurentHa** [comment]
Hello, I'm new here !
But, just to tell you if you are looking for help with localizations, I can help you in French ;-)
Sincerely, Lau.

**Comment by LaurentHa** [comment]
@RemixDev 
Hello, I'm new here !
But, just to tell you if you are looking for help with localizations, I can help you in French ;-)
Sincerely, Lau.

**Comment by LaurentHa** [comment]
@RemixDev 
Hello, I'm new here !
But, just to tell you if you are looking for help with translations, I can help you in French ;-)
Sincerely, Lau.

**Comment by RemixDev** [comment]
Localization support added in development branch

**Comment by LaurentHa** [comment]
@RemixDev I see you added localization in the development branch. Do you need my help for translating the app in French ? If yes, please tell me how can I get the strings to translate and send them back to you translated in French ?

**Comment by RemixDev** [comment]
https://notabug.org/RemixDevs/DeezloaderRemix/raw/development/app/public/locales/en.json

**Comment by RemixDev** [comment]
Then send it to me on Telegram or make a pull request on notabug

**Comment by LaurentHa** [comment]
@RemixDev I just finished the french translation ! I tried to make a pull request on NotaBug, but the button to do it is greyed out ! Can you say me how to do ? Sorry but I don't have Telegram...

**Comment by RemixDev** [comment]
You need to fork the repo, add the file in the development branch and then make a pull request

**Comment by LaurentHa** [comment]
Hey ! I think I uploaded my french translation correctly ! But there was another one already uploaded by someone else. I think my translation is better for the exact words in English and is more understandable. You can select it without fear :-) Lau.
