### ISSUE TITLE
Add option to postprocess audio

### ISSUE THREAD

**Issue by w3bb** [RemixDev/DRemixIssues#73]
It sucks having only having two formats (mp3 and FLAC), and having no easy way to convert your library to another format.

An option to postprocess/convert audio after download would fix this. It would be more flexible than the standard format options, with support for customization like bitrate and codec/container. Ideally it would download the FLAC (or optionally mp3) file of a song and convert it using that as a source.

It could be a gui option or perhaps you could write a custom ffmpeg command from the settings menu to use.

Personally for someone who uses Opus to save space this would save a lot of sweat and tears.

**Comment by RemixDev** [comment]
The app scope is to get what deezer is offering and not modify that in any way.
So wontadd

**Comment by omgwtfbbqpls** [comment]
I'm hoping someone can fork this or whatever, opus would be quite a useful feature.

**Comment by w3bb** [comment]
@omgwtfbbqpls Yeah. Now that I think about it what if there was an option to automatically run a command on all downloaded files? It would be really helpful even outside of transcoding.
