### ISSUE TITLE
Able to download mp3 with CBR Bitrate

### ISSUE THREAD

**Issue by fleshripper** [RemixDev/DRemixIssues#74]
**Is your feature request related to a problem? Please describe.**
The USB in the car only reads CBR files, if they are VBR I get a device error.

**Describe the solution you'd like**
Be able to get the files directly with CBR Bitrate.

**Comment by RemixDev** [comment]
The app already downloads CBR MP3 files. There is no option for VBR files.
Only FLAC files are downloaded in VBR.
