### ISSUE TITLE
Error: Track is Empty

### ISSUE THREAD

**Issue by NiiKox** [RemixDev/DRemixIssues#75]
i cant dowload song on FLAC https://www.deezer.com/track/734393362?utm_source=deezer&utm_content=track-734393362&utm_term=2015574166_1572827184&utm_medium=web 

i select MP3 320kb y can dowload Is there a solution to this problem?

**Comment by RemixDev** [comment]
Fixed in latest beta:
commit [`2db05405b4`](https://notabug.org/RemixDevs/DeezloaderRemix/commit/2db05405b4eefe93190eb96d5f4dee373d5533cd)

**Comment by NiiKox** [comment]
no work :(

**Comment by RemixDev** [comment]
Track is empty is a generic error that is caused by the track not being available on deezer.
With the latest commit it tries to download the mp3 instead.
