### ISSUE TITLE
Feature Request: Playlist enhancements (compilations)

### ISSUE THREAD

**Issue by RandomNinjaAtk** [RemixDev/DRemixIssues#76]
**Is your feature request related to a problem? Please describe.**

1. Files are not tagged with the same album artist and instead tagged organized by the playlist creator/name
2. Year is set at individual track level, so when used as part of the album folder, you get multiple folders...
3. Using album_id in album folder name can result in multiple folders
4. Tracks are not using playlist position as track number, resulting in multiple tracks with the same track number

**Describe the solution you'd like**

1. All tracks should have the album artist set to "Various Artists"
2. If possible, set the year, to the date/year the playlist was created
3. Set the track number to the playlist position number
4. Set album_id to playlist ID number

**Describe alternatives you've considered**
Manually updating the files and moving them to the correct folder

**Comment by RemixDev** [comment]
I thought all this were already implemented (except for number one which I don't know if I will implement it)

**Comment by RandomNinjaAtk** [comment]
Maybe it works for mp3? I want to say it looked like MP3 files maybe had the corrections, but not the flac files.

**Comment by RemixDev** [comment]
Added with commit [`d49e9ee36d`](https://notabug.org/RemixDevs/DeezloaderRemix/commit/d49e9ee36dc78109baa695c6dd353d6b6728dd91)
