### ISSUE TITLE
Artwork Enhancement - Embedded and Local Quality Setttings

### ISSUE THREAD

**Issue by RandomNinjaAtk** [RemixDev/DRemixIssues#77]
**Is your feature request related to a problem? Please describe.**
Yes/No, right now all artwork is set to a given size which can result in a lot of extra data usage when using the maximum size setting. Would be nice to store the local jpg/png as the maximum size, and set the embedded size to a lower quality.

**Describe the solution you'd like**
Create new settings to more finely control downloaded artwork, example:

1. Local album/artist artwork file is downloaded at 2000x2000 png/jpg (or set as desired)
2. Embedded album file artwork is downloaded at 1000x1000 (or set as desired)

This allows the files to be smaller by embedding a lower quality version, while also keeping the highest quality available locally as a separate file.

**Describe alternatives you've considered**
A lot of manual editing/work..

**Comment by RemixDev** [comment]
Added with commit [`6dbe7b8ac6`](https://notabug.org/RemixDevs/DeezloaderRemix/commit/6dbe7b8ac67e1fde8d9632739ea090ccf9f8e9d1)
