### ISSUE TITLE
CLI impementation for scripting automation (non-interactive)

### ISSUE THREAD

**Issue by RandomNinjaAtk** [RemixDev/DRemixIssues#78]
**Is your feature request related to a problem? Please describe.**
Sort of, there isn't an easy way to automate using scripts with the current software

**Describe the solution you'd like**
A CLI implementation for passing requests to the application. This does not need to be interactive, but this would be used enable automation via scripts.

Example script using other software:
https://github.com/Migz93/lidarr-download-automation

**Describe alternatives you've considered**
Using other software for automated processing

**Additional context**

**Comment by RemixDev** [comment]
Making this app work in cli mode would require a total rewrite of the app from the ground up

I suggest using other projects, like [chimera](https://notabug.org/Aesir/chimera)

**Comment by RandomNinjaAtk** [comment]
Thanks for the feedback, I've used other projects for automation, but this has been such a great project that I wanted to be able to do similar things with it.
