### ISSUE TITLE
Big tracks fail to download

### ISSUE THREAD

**Issue by TheUltimateC0der** [RemixDev/DRemixIssues#84]
**Describe the bug**
Downloading of Big tracks fails

**To Reproduce**
- Search for "Monstercat" as Artist
- Download all of the stuff

**Expected behavior**
Not throwing exceptions and downloading stuff

**Desktop (please complete the following information):**
 - OS: Docker (https://hub.docker.com/r/bocki/deezloaderrmx/)
 - Version: 4.2.2
 - Did you build it from the repo?: Nope
 - If so which branch?: According to the DockerFile it is develop

**Log File**
```
[Error] RangeError: Invalid string length
    at Array.join (native)
    at Request.<anonymous> (/deezloaderremix/app/node_modules/request/request.js:1147:31)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/deezloaderremix/app/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by RemixDev** [comment]
Can you recreate the same issue without using docker and using the latest beta?

**Comment by TheUltimateC0der** [comment]
Yes

**Comment by TheUltimateC0der** [comment]
Try this for example. https://www.deezer.com/en/album/105316722

The last track has a duration of 136:52.

**Comment by RemixDev** [comment]
Tested with the latest commit on development branch
Can't recreate

**Comment by Skaronator** [comment]
The latest dev branch version did indeed fix this issue. @TheUltimateC0der you can switch to the `latest-dev` branch in Docker.

**Comment by TheUltimateC0der** [comment]
I forked the repo (https://github.com/TheUltimateC0der/deezloadermx-docker) and created my own docker image, which installs the latest Deezloader Remix from dev branch on every restart. You can find it here: https://hub.docker.com/r/theultimatecoder/deezloaderremix
