### ISSUE TITLE
Add a YEAR tag to FLAC files

### ISSUE THREAD

**Issue by ExtendLord** [RemixDev/DRemixIssues#86]
Windows Explorer displays the Year property from YEAR tag on FLAC files
If you download a FLAC file from Deezloader Remix, you will see that there is no Year
![Untitled](https://user-images.githubusercontent.com/26222159/68646633-6fbf7000-0524-11ea-9620-ecdefa404f87.png)
A solution is to add a YEAR tag to FLAC files.

**Comment by RemixDev** [comment]
Year is not a standard vorbis comment.
Won't add
