### ISSUE TITLE
Different downloading rules for albums and single songs

### ISSUE THREAD

**Issue by Draly** [RemixDev/DRemixIssues#91]
It would be nice to have an option to create artist and album folders only when downloading albums, so that when you download a few songs you like, they won't be saved at the same place that albums do.
Maybe an option to bypass artist and album folders creation, but instead something like "put single songs in a specified folder" where you can enter the name you want (but "Singles" would suit my need perfectly).
Would be great to organize audio colletion.
"Artist\year - Album\Track number - Title" for albums
"Singles (or whatever you want)\Artist - Title"
For example.

**Comment by RemixDev** [comment]
Added with commit [`6dbe7b8ac6`](https://notabug.org/RemixDevs/DeezloaderRemix/commit/6dbe7b8ac67e1fde8d9632739ea090ccf9f8e9d1)
