### ISSUE TITLE
Simple REST API

### ISSUE THREAD

**Issue by TheUltimateC0der** [RemixDev/DRemixIssues#93]
**Is your feature request related to a problem? Please describe.**
I want a way to automate downloading of `tracks` `albums` `artists` via a simple REST call

**Describe the solution you'd like**
I like to have a REST endpoint per object (`artist`, `album`, `track`, `playlist`) where I can post a name or Deezer Id to automatically add things for downloading.

GET
`https://mydeezloader.instance.tld/api/download/{object}/{DeezerId}`
or
POST
`https://mydeezloader.instance.tld/api/download/{object}`
```
{"id": "{DeezerId}"}
```

**Describe alternatives you've considered**
I found no alternatives so far

**Additional context**
This way, I can build an application to automate downloading of new releases

**Comment by RemixDev** [comment]
I have no idea how to do that

**Comment by TheUltimateC0der** [comment]
What exactly?

The REST API?
How to trigger the download when a REST call triggers?

**Comment by RemixDev** [comment]
Everything
I think I know how to make a REST API but I'm not sure if I'm right
Also I have no idea how to link the app to the rest API (if it works with socket.io then there is no problem)

**Comment by nomis6432** [comment]
I don't think you need to create a REST API for this use case. You can just write your own socket.io client that connects to the deezloader backend (port 1730 by default). Check /app/app.js (the backend) to see all possible events you can send to the server. "downloadtrack" f.e. will download a given track with data.id the ID of the track. I'd suggest checking out /app/public/js/frontend.js to see how these emits work. You'll also have to login first before you'll be able to download anything.

**Comment by RemixDev** [comment]
Added with latest commit

**Comment by TheUltimateC0der** [comment]
Thanks @selfhoster for the implementation!

**Comment by selfhoster** [comment]
No worries, I also want it for automation purposes.
The /download/ and /search/ APIs should be enough for most usecases, but let me know if there is anything else the app does that makes senses to also be added to the APIs.

**Comment by TheUltimateC0der** [comment]
An endpoint for the amount of items in the queue would be awesome!

**Comment by selfhoster** [comment]
[pull request](https://notabug.org/RemixDevs/DeezloaderRemix/pulls/448)
[commit](https://notabug.org/selfhoster/DeezloaderRemix/commit/3a757be2d6ef775914e004564ce4ff8881ad524f)
