### ISSUE TITLE
ID tags: Old date format  (only YEAR).

### ISSUE THREAD

**Issue by doomlord77** [RemixDev/DRemixIssues#94]
Back then,  there was an option "ID3 Default" and it saved only the year for the date format. For a while now I can choose only YY.MM.DD or variations of this.

Solution: bring back ID3 Deafult as an option, please.

**Comment by RemixDev** [comment]
For MP3s ID3 Default is the only option right now
The date format setting is only for FLAC files

**Comment by doomlord77** [comment]
> For MP3s ID3 Default is the only option right now
> The date format setting is only for FLAC files

But ID3 Deafult for FLAC would be great

**Comment by RemixDev** [comment]
But it's not meant for FLACs
Also the YEAR tag for FLACs is not a standard vorbis comment, so it won't be added again.
