### ISSUE TITLE
Bug when downloading a track from the right click context menu

### ISSUE THREAD

**Issue by EduMoreno142** [RemixDev/DRemixIssues#95]
**Describe the bug**
When you download a track by right clicking it and choosing a quality, the UI restarts

**To Reproduce**
1. Search any track (not sure if album/artist/playlist do the same thing)
2. Right click on it and choose any quality
3. The track is added to the downloads, but the UI restarts

**Expected behavior**
UI not restarting

**Comment by RemixDev** [comment]
Fixed in commit e14125dd72
