### ISSUE TITLE
UI restarts after closing modal

### ISSUE THREAD

**Issue by andtit2001** [RemixDev/DRemixIssues#96]
**Describe the bug**
When you close "Artist" or "Album" window, UI restarts.

**To Reproduce**
1. Search for any song
2. Click on "Artist" or "Album" link
3. Close the opened modal

**Expected behavior**
UI do not restart.

**Additional context**
1. This bug has appeared on the latest published beta version
2. This issue is closely related with #95

**Comment by RemixDev** [comment]
Fixed in commit e14125dd72
