### ISSUE TITLE
Discography Download

### ISSUE THREAD

**Issue by Gargantua01** [RemixDev/DRemixIssues#98]
When downloading discography of an artist can you make the download sequence sort in alphabetical order, as sometimes an album or single may fail... and it can be helpful by running the downloads folder side by side with the download list to see whats missing... I am aware of the error logs creation feature... but this can be helpful as well, and huge thumbs up for the android app enhancements, album covers looks great in the download section.

**Comment by RemixDev** [comment]
Adding stuff in the download queue is asynchronous so it can't be ordered
Can't add

**Comment by RemixDev** [comment]
Adding albums to queue is asynchronous and can't be ordered
