### ISSUE TITLE
Search for alternatives if a track is not available at a desired bitrate

### ISSUE THREAD

**Issue by Derp0** [RemixDev/DRemixIssues#99]
Try to search and download an alternative of a track if it's not available at the selected bitrate and " fall to lower bitrate" is disabled in the settings, it currently just throws an error.

**Comment by RemixDev** [comment]
Added with commit [`d9994b72b1`](https://notabug.org/RemixDevs/DeezloaderRemix/commit/d9994b72b17d04963d79105f36a86b5a78665c6b)
